### ISSUE TITLE
User has to provide offset to get time local time

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-library#1138]
**Description:**
If the user knows his/her timezone `"Asia/Colombo"` ballerina can keep track of default offsets. There are default timezone data used in other languages.

eg: IANA Time Zone Database (TZDB)

Currently user has to provide all of these.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
Time zones are not yet supported in Ballerina. We are currently working on the design.

**Comment by TharmiganK** [comment]
Closing this since we have support for Zone APIs
