### ISSUE TITLE
time:civilToString doesn't work when called with Civil converted from Utc

### ISSUE THREAD

**Issue by daoxxx** [ballerina-platform/ballerina-library#2846]
I try to get string representation of time after conversion from UTC to Civil. This code 
```
import ballerina/io;
import ballerina/time;
        
public function main() returns error? { 
    string dateFrom = "2022-04-15T10:00:00+03";
    time:Civil startDate = check time:civilFromString(dateFrom);
    time:Utc startDateUtc = check time:utcFromCivil(startDate);
    time:Utc blockUtc = time:utcAddSeconds(startDateUtc, -60*15);
    time:Zone? zone = time:getZone("Europe/Moscow");
    if zone is time:Zone {
        time:Civil block = zone.utcToCivil(blockUtc);
        io:println(block);
        string blockstring = check time:civilToString(block);
        io:println(blockstring);
    }   
}
```
outputs
```
{"timeAbbrev":"Europe/Moscow","dayOfWeek":5,"year":2022,"month":4,"day":15,"hour":9,"minute":45,"second":0}

error: civil.utcOffset must not be null
```
utcToCivil() doesn't fill utcOffset field, only the timeAbbrev one.
I tried to get offset value with Zone.fixedOffset() and that returned nil (maybe because it's not fixed for this time zone).
So, the only way i could invent is to hardcode offset value after conversion
```
time:Civil block = zone.utcToCivil(blockUtc);
block.utcOffset = {"hours":3};
```
This time worked
```
2022-04-15T06:45:00Z
```
But formatted time is in UTC instead of expected localized time "2022-04-15T09:45:00+03:00".

How can i obtain proper RFC 3339 formatted time in local time zone?

I guess time:Zone.civilToString() method should get utcOffset from system using timeAbbrev field?

**Comment by BuddhiWathsala** [comment]
@daoxxx, ATM  we don't have an API to achieve that. Yes, as you have mentioned, a `time:Zone.civilToString()` will solve the problem.
