### ISSUE TITLE
Add support for Electronic Data Interchange (EDI)

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-library#2857]
**Description:**
Refer to the  draft here https://github.com/ballerina-platform/ballerina-standard-library/issues/2674

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
This is available from EDI CLI
