### ISSUE TITLE
Server Sent Events (SSE) support 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-library#3188]
https://en.wikipedia.org/wiki/Server-sent_events

**Comment by shafreenAnfar** [comment]
On the service side we can do something similar to the below.

```ballerina
import ballerina/http;

type SseEvent record {
    string id?;
    string event?;
    string[] data;
};

service / on new http:Listener(9090) {

    resource function get greeting() returns stream<SseEvent> {
        stream<SseEvent> sseEvents = from var data in ["Hello", "World"] select {
            data: [data]
        };
        return sseEvents;
    }
}
```
On the client side we can simply mirror that.

```ballerina
import ballerina/http;

type SseEvent record {
    string id?;
    string event?;
    string[] data;
};

public function main() returns error? {
    http:Client greetingClient = check new ("localhost:9090");

    stream<SseEvent> greetings = check greetingClient->/greeting;
}
```

**Comment by rukmal** [comment]
+1. many Foundation Model providers use SSEs exclusively for their streaming APIs:

- OpenAI: https://platform.openai.com/docs/api-reference/chat/streaming
- Anthropic: https://docs.anthropic.com/claude/reference/streaming
- Cohere: https://github.com/cohere-ai/cohere-python/blob/main/examples/streaming_demo.ipynb

It's unfortunate that this is the case, but it doesn't look like SSEs are going away any time soon.

@shafreenAnfar's approach works. Is this the recommended way to handle SSE APIs in Ballerina?

**Comment by xlight05** [comment]
> +1. many Foundation Model providers use SSEs exclusively for their streaming APIs:
> 
> * OpenAI: https://platform.openai.com/docs/api-reference/chat/streaming
> * Anthropic: https://docs.anthropic.com/claude/reference/streaming
> * Cohere: https://github.com/cohere-ai/cohere-python/blob/main/examples/streaming_demo.ipynb
> 
> It's unfortunate that this is the case, but it doesn't look like SSEs are going away any time soon.
> 
> @shafreenAnfar's approach works. Is this the recommended way to handle SSE APIs in Ballerina?

+1 on the use case. 
Currently, AI teams are also having the same requirement.  
Currently, When we are using the azure openai connector fails when we turn stream=true because of this.

**Comment by MohamedSabthar** [comment]
Implemented. Refer https://github.com/ballerina-platform/ballerina-library/issues/6687
