### ISSUE TITLE
Adding OpenAPI config to the service returns OOM

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#3195]
**Description:**
$subject

Related to [#132](https://github.com/wso2-enterprise/internal-support-ballerina/issues/132)

**Comment by ayeshLK** [comment]
When generating the OpenAPI specification for an HTTP service of a reasonable size there will be an out of memory error while writing the generated OpenAPI spec to `openApiDefinition` field of `http:ServiceConfig` annotation. 

Since our original problem was that we could not identify the proper resource path at runtime for the generated resources, runtime team has suggested to use CodeModifiers to pass that information into runtime [1]

@shafreenAnfar / @chalitha1989 WDYT ?

[1] - [https://github.com/wso2-enterprise/internal-support-ballerina/issues/132#issuecomment-1189295992](https://github.com/wso2-enterprise/internal-support-ballerina/issues/132#issuecomment-1189295992)

**Comment by chamil321** [comment]
> When generating the OpenAPI specification for an HTTP service of a reasonable size there will be an out of memory error while writing the generated OpenAPI spec to `openApiDefinition` field of `http:ServiceConfig` annotation.
> 
> Since our original problem was that we could not identify the proper resource path at runtime for the generated resources, runtime team has suggested to use CodeModifiers to pass that information into runtime [1]
> 
> @shafreenAnfar / @chalitha1989 WDYT ?
> 
> [1] - [wso2-enterprise/internal-support-ballerina#132 (comment)](https://github.com/wso2-enterprise/internal-support-ballerina/issues/132#issuecomment-1189295992)

We have to think twice before using the code modifier as there is a possibility of having lang OOM(Ongoing issue)

**Comment by ayeshLK** [comment]
Fixed this bug with following PR:
- https://github.com/ballerina-platform/openapi-tools/pull/1643
