### ISSUE TITLE
Add constraint support for path, query and header params

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-library#3239]
**Description:**
$subject

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
Adding [this issue](https://github.com/ballerina-platform/ballerina-standard-library/issues/3998) as a part of this effort

**Comment by TharmiganK** [comment]
Path parameter example from the above issue:
```ballerina
# Get a specific user
# 
# + id - The user ID of the user to be retrived
# + return - A specific user or error message
resource function get users/[@int{minValue = 0} int id]() returns User|error {
    User|error result = self.userDb->queryRow(`SELECT * FROM USER_DETAILS WHERE ID = ${id}`);
    if result is sql:NoRowsError {
        return error UserNotFoundError("id: " + id.toString());
    } else {
        return result;
    }
}
```

**Comment by TharmiganK** [comment]
- [ ] As a first step, we should allow constraint validation for the types which already have constraints. For example:
    ```bal
    @constraint:Int {minValue: 0}
    type Id int;
    
    resource function get users/[Id id]() returns User|error {
        ...
    }
    ```
    - The responses should be `400-BadRequest` for query and header constraint validation errors and `404-NotFound` for path parameter constraint validation errors.


- [ ] As the next step, we should allow constraint validation for resource parameters with constraints in-line. For Example:
   ```bal
   resource function get users/[@int{minValue : 0} int id]() returns User|error {
      ...
   }
   ```
   - This requires the support from the constraint module - tracked via https://github.com/ballerina-platform/ballerina-standard-library/issues/4341
   - When we allow this the validation is going to be internal and it is an **additional constraint validation** compare to what we do in the first step. Consider the following example:

      ```bal
      @constraint:Int {minValue: 0}
      type Id int;
      
      // Validate the maxValue by reading the parameter annotation and
      // validate minValue by reading the annotation from the parameter type
      resource function get users/[@int{maxValue : 100} Id id]() returns User|error {
         ...
      }
      ```
      For this we need the compiler plugin support as well. Currently, we don't allow annotations from any other modules. In addition, if we are supporting in-line constraint annotation support, then we need to add this additional validation for the payload parameter as well.
      
      There are some concerns regarding this implementation:
      
      1. If we do these two constraint validations then there is no way to validate something like `maxValue` should be greater than `minValue`. But we could leave it to the user.
         
      2. This second validation should be done with the value, the annotation we obtain from the parameter, and the type of the parameter(this is need to find the matching validator type). Currently constraint module only expose the `validate` function which accepts a value and a `typedesc`. So we might want an API from constraint to support this. (We could built a `typeref` with the type and the annotation, but it is not **ideal** because in Ballerina, the annotation on a function parameter is different from having an annotation on a parameter type)
         
      3. It is not straightforward to get the parameter annotation from the `BalResource` since it keeps the annotations and the parameters separately. So we have to filter them(by the parameter name) or ballerina lang should provide a support to directly obtain the annotation from a parameter.

**Comment by shafreenAnfar** [comment]
Supporting the first step is enough.

**Comment by TharmiganK** [comment]
Closing this since the requirement is to implement step 1 which is available in https://github.com/ballerina-platform/ballerina-library/issues/4371
