### ISSUE TITLE
Add API docs for generated persist clients

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#3502]
**Description:**
Users are going to interact with a specific generated client for an Entity. Even though the APIs are same (except the entity type), it would add great value for the first time experience if the client comes with base API docs.

**Describe your task(s)**
- [x] Finalise the API doc template to use for generated clients
- [ ] improve `persist generate` command to include API docs

**Comment by niveathika** [comment]
This is on hold due to persist module design V2

**Comment by niveathika** [comment]
Entity Definition:
```ballerina
type Workspace record {|
    readonly string workspaceId;
    string workspaceType;
    Building location; // 1-n relation (parent)
    Employee employee; // 1-1 relation (child)
|};
```

Generated Types:
```
# Entity `Workspace` as defined in the data store. `buildingBuildingCode` is the foreign key column of the `Building` relation
public type Workspace record {|
    readonly string workspaceId;
    string workspaceType;
    string buildingBuildingCode;
|};

# This is used to insert `Workspace` entity
public type WorkspaceInsert Workspace;

# This is used to update `Workspace` entity. Fields with values will be updated in the specific record in the data store.
public type WorkspaceUpdate record {|
    string workspaceType?;
    string buildingBuildingCode?;
|};
```

**Comment by niveathika** [comment]
As per the offline discussion we decided to hold this until the client/types becomes complex. At this point all the types and client APIs are self explanatory.

**Comment by daneshk** [comment]
As per the above comment, we don't need to add API docs for the generated client. Hence closing the issue. Will open the issue, if we got a requirement.
