### ISSUE TITLE
Check GraalVM support failures in std libs

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-library#3755]
**Description:**

The following standard libraries are failing with `bal test --native`. Need to check the reason and fix them.

**Describe your task(s)**

| Module | Reason for the failures | Related issue(s) | Fix Status |
|--------|------------------------|-----------------|:--------:|
|log|testerina native test limitation with mocking|[ballerina-lang#39040](https://github.com/ballerina-platform/ballerina-lang/issues/39040)|✅|
|http|OOM due to 1500+ test cases|[#3718](https://github.com/ballerina-platform/ballerina-standard-library/issues/3718)|✅|
|udp|only fails on windows, seems to be intermittent|https://github.com/ballerina-platform/ballerina-standard-library/issues/3956| ✅ |
|ftp|due to this library `org.apache.sshd` used in `test-utils`|https://github.com/ballerina-platform/ballerina-standard-library/issues/3958| ✅ |
|auth|some missing configs|N/A|✅|
|file|hangs on windows|[ballerina-lang#39121](https://github.com/ballerina-platform/ballerina-lang/issues/39121)|✅|
|http|hangs on windows|[ballerina-lang#39121](https://github.com/ballerina-platform/ballerina-lang/issues/39121)|✅|
|websub|hangs on windows|[ballerina-lang#39121](https://github.com/ballerina-platform/ballerina-lang/issues/39121)|✅|
|graphql|hangs on windows|[ballerina-lang#39121](https://github.com/ballerina-platform/ballerina-lang/issues/39121)|✅|
|kafka|hangs on ubuntu|[ballerina-lang#39121](https://github.com/ballerina-platform/ballerina-lang/issues/39121)|✅|
|rabbitmq|hangs on ubuntu|[ballerina-lang#39121](https://github.com/ballerina-platform/ballerina-lang/issues/39121)|✅|
|mssql|some missing configs|N/A|✅|
|nats|some tests failed on ubuntu|https://github.com/ballerina-platform/ballerina-standard-library/issues/3957| ✅ |
|http|fails on windows without test report|[ballerina-lang#38882](https://github.com/ballerina-platform/ballerina-lang/issues/38882)|✅|
|graphql|fails on windows without test report|[ballerina-lang#38882](https://github.com/ballerina-platform/ballerina-lang/issues/38882)|✅|
|java.jdbc|fails on windows without test report|[ballerina-lang#38882](https://github.com/ballerina-platform/ballerina-lang/issues/38882)| ✅ |
|grpc|fails on windows without test report|[ballerina-lang#38882](https://github.com/ballerina-platform/ballerina-lang/issues/38882)|✅|
|websocket|fails on windows without test report|[ballerina-lang#38882](https://github.com/ballerina-platform/ballerina-lang/issues/38882)|✅ |
|sql|OOM due to transaction test cases|[ballerina-lang#38826](https://github.com/ballerina-platform/ballerina-lang/issues/38826)| ✅ |
|java.jdbc|OOM due to transaction test cases|[ballerina-lang#38826](https://github.com/ballerina-platform/ballerina-lang/issues/38826)| ✅ |
|mysql|OOM due to transaction test cases|[ballerina-lang#38826](https://github.com/ballerina-platform/ballerina-lang/issues/38826)| ✅ |
|oracledb|OOM due to transaction test cases|[ballerina-lang#38826](https://github.com/ballerina-platform/ballerina-lang/issues/38826)| ✅ |

**Comment by dilanSachi** [comment]
@TharmiganK We can close this right?

**Comment by TharmiganK** [comment]
Fixed with the above PRs
