### ISSUE TITLE
Github Release is not published with StdLib Release Workflow

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-library#4540]
**Description:**
In `mime` and `kafka` modules, GitHub releases were not published with stdlib release pipeline in u6 release. However, the release tag, branch, and the central push were successful. Only the GitHub release was missing.

Workflow logs:
- https://github.com/ballerina-platform/ballerina-standard-library/actions/runs/5140346636/jobs/9251719964#step:4:117
- https://github.com/ballerina-platform/ballerina-standard-library/actions/runs/5142823181/jobs/9257040797#step:4:90

**Comment by ThisaruGuruge** [comment]
This probably is an issue with GitHub itself. We can check this during the next release to confirm.

**Comment by ThisaruGuruge** [comment]
Clsoing this issue since this seems to be an intermittent issue from the GitHub actions. We can not do anything about this atm.
