### ISSUE TITLE
Migrating GitHub Workflows to the Central Ballerina Standard Library Repository

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-library#4778]
**Description:**
Create the templates for Release, Central Publish, Build, and Pull Request workflows within the Ballerina Standard Library Repository. These templates will be available for reference by the workflows in individual standard libraries and connectors.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Closing as this is now completed
