### ISSUE TITLE
OpenAPI Tool Omits Types Defined in Modules from the Generated Specification

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-library#4805]
**Description:**
When generating the OpenAPI spec for the service that has input parameters defined in a sub-module, it completely omitted the types defined in the sub-modules in the resulting specification file.

Steps to reproduce the issue can be found here: https://discord.com/channels/957996897782616114/1151957139158478898/1151957139158478898

**Comment by TharmiganK** [comment]
Fixed via https://github.com/ballerina-platform/openapi-tools/pull/1564
