### ISSUE TITLE
Re-implement Amazon AWS SNS Connector

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-library#4846]
**Description:**
This is the main task to track the re-implementation of the AWS SNS connector as a part of the Ballerina connector revamp effort

- [x] [Research into AWS SNS and use cases](https://docs.google.com/document/d/1e-AnO7iSCFVaNtOfBiCWKqNeO41fxbgevnh3UEGxNd8/edit?usp=sharing)
- [x] Test and familiarize with existing connector
- [x] [Design documentation for implementation](https://github.com/ballerina-platform/ballerina-standard-library/issues/4845)
- [x] Implementation & test cases
- [x] Documentation
- [x] Examples

**Comment by daneshk** [comment]
The implementation is already. Hence closing the issue
