### ISSUE TITLE
bal openapi --client-methods default value is declared as remote, but in fact is resource

### ISSUE THREAD

**Issue by yuriylesyuk** [ballerina-platform/ballerina-library#4878]
**Description:**

The help text for bal openapi --client-methods default method is factually incorrect. It says `remote`, but is `resource`.

**Steps to reproduce:**

When --help is displayed, states that the default option is *remote*. 
```
$ bal openapi --help
...
        --client-methods <resource|remote>
            This option can be used in client generation to select the client method type, which can be `resource` or `remote`. (The default option is `remote`).
...
```
In reality, for a command to generate client stubs:
```
$ bal openapi -i swagger-20.json --mode client
```

The client.bal file contains function signatures with resource declaration.Example:

```
<snip>
    # + return - Successful response 
    resource isolated function get b/[string bucket]/acl/[string entity]("json" alt = "json", string? fields = (), string? 'key = (), string? oauth_token = (), boolean prettyPrint = true, string? quotaUser = (), string? userIp = (), string? uploadType = (), string? userProject = ()) returns BucketAccessControl|error {
        string resourcePath = string `/b/${getEncodedUri(bucket)}/acl/${getEncodedUri(entity)}`;
<snip>
```

To generate remote functions, we need to use `--client-methods=remote option`,
which works, but the `remote` is a better default.

**Affected Versions:**

the latest bal command:
```
$ bal --version
Ballerina 2201.7.2 (Swan Lake Update 7)
Language specification 2023R1
Update Tool 1.3.15
```

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
PR : https://github.com/ballerina-platform/ballerina-lang/pull/42570

**Comment by lnash94** [comment]
We update the our help text via this PR : https://github.com/ballerina-platform/ballerina-lang/pull/42570
