### ISSUE TITLE
Support code generation to Ballerina PreBuildRunner task within the OpenAPI tool

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#4932]
**Description:**
This design considers a bal tool configuration as a build input. Such build inputs can be provided as CLI args, config elements in Ballerina.toml, or directly in the source code. The most obvious choice is the Ballerina.toml.
This needs to be applied to 

- [x] #5822
- [ ] #5823
- [ ] Service type generation

**Comment by lnash94** [comment]
Client generations: 

While doing the client generation implementation, I encountered the following challenges 
- Issue with assainged tool-id when introduce a schema to validate the options specific to the tool as a root level resource. ex: `<tool-type>-<tool-id>-options-schema.json`, Here tool-id can not be assigned within the tool since it is supposed to be added within user input in Ballerina.toml
- There is no method to access the `packageInstance` instance within toolContext although it include package within itself. https://github.com/Dilhasha/ballerina-lang/blob/da2c28c9b9bf072e7efaec84b667207c17fad3e1/compiler/ballerina-lang/src/main/java/io/ballerina/projects/ToolContext.java#L30
@Dilhasha , @ShammiL FYI

**Comment by lnash94** [comment]
- A package instance alone may not suffice to obtain the resolved OpenAPI contract path, especially when it involves a relative path. It would be more convenient if we could access the resolved input file path within the ToolContext. 
With this information available in the OpenAPI tool, file validation can be handled within the openAPI tool, whether the tool can support the given file type.

**Comment by ShammiL** [comment]
It is possible to get the resolved input file path using the relative input file path from `ToolContext` (`ToolContext.filePath()`) and the path to source root from the package (`Package.project().sourceRoot()`).

**Comment by lnash94** [comment]
Discussion to service generations:
- When service generation we only created a service skeleton and the user needs to implement the resource function body with their requirements, therefore are we going to add this service generation to there?
- We have a service type generation option along with service generation mode, here we provide a service Skelton file, and a service type file as generated codes. Are we supposed to introduce another flag to generate service type only without generating service Skelton and integrate it into the bal task?

**Comment by lnash94** [comment]
As discussed, validation for the file input path, and target path will be handled via the plugin itself.

**Comment by ShammiL** [comment]
The toml properties for build tools in `Ballerina.toml` will be validated as follows:

- `id`, `filePath`, and `targetModule` properties are mandatory.
- Values provided for `id`, `filePath`, and `targetModule` properties must be string values.
- `id` and `filePath` property values cannot be empty. 
- If `targetModule` value is empty, the default module will be considered as the targetModule.

**Comment by lnash94** [comment]
Meeting date: 2023/11/14
Attendees : @sameerajayasoma, @hevayo, @daneshk, @Dilhasha, @azinneera, @lnash94, @dilanSachi

- The end of December will be the deadline for phase 1 package build integration task for tools.
- We have decided to prioritize completing OpenAPI client generation for package builds by the aforementioned deadline.

Our implementation plan includes the following key components within the OpenAPI tool in phase 1.

-  Integration to package build by manually adding tool configurations
- `bal openapi add` command for updating Ballerina.toml with tool config element
- A caching mechanism within the OpenAPI tool for package build integration

**Comment by lnash94** [comment]
Suggested subcommand

This command is used to only update the Ballerina.toml with the command line details,; no code generation happens

> `bal openapi add`

**Command options**

- --module <target-module-name> : The default is the root module 
- --id <config-id-in-ballerina-code>: Generate a sensible default id
- --package <path-to-the-package>: The default is “.”
- --mode <client|service>:  The default mode is “client”
- --tags <list of tags> : optional
- --operations <list of operations>: optional
- --nullable <boolean value> : optional
- --license  <license path>: added DO NOT MODIFIED header

**Comment by lnash94** [comment]
We encounter a concern with the 'targetModule' value when the user has provided the same target module in two different config elements. In this case, the generated client will override the target module. This scenario can occur when the same tool has the same target module, and two tools share the same target module.

**Comment by ShammiL** [comment]
The following changes were to the tool integration implementation with the recent improvements:
- The optional configurations provided in the `Ballerina.toml` as `options.*` can be accessed from within the tool using `ToolContext .options()` which returns the configurations as a `Map<String, Object>`.
- The interface to be implemented by the tool has been renamed to `io.ballerina.projects.buildtools.CodeGeneratorTool` instead of `io.ballerina.cli.tool.BuildToolRunner`. 
- Following scenarios will result in a compilation failure:
    1. Ballerina.toml validation failures in tool configurations
    2. Tool not found for execution
    3. Errors reported during tool execution

More details  on these changes are documented in the [developer guide](https://docs.google.com/document/d/1SoQzDPznIs9KuIAE9cNcLPP_OM-ELGGashn-DEruzO4/edit?usp=sharing).

**Comment by lnash94** [comment]
Currently, we need option locations for generating the diagnostics, with new changes we have limitations to getting location from the tool context since we receive `Map<String, Object>`.

**Comment by ShammiL** [comment]
This is fixed in https://github.com/ballerina-platform/ballerina-lang/pull/42168
`ToolContext.Options()` will return a `Map<String, Option>` where `Option` will contain both the option value and its toml node location.
Check https://github.com/ShammiL/sample-build-tool for usage examples

**Comment by lnash94** [comment]
If we publish the openapi tool to the central, will it affect this feature with conflicts ?

**Comment by ShammiL** [comment]
> @Dilhasha, @ShammiL If we publish the openapi tool to the central, will it affect this feature with conflicts?

The current implementation assumes that the distribution provided tools cannot be accessed through the Central. If this were to be supported it would introduce other complications in other areas like tool resolution, compiler plugin resolution and language server and would require a lot of re-designing in the mentioned areas. 
Hence, publishing OpenAPI tool to Central would result in conflicts.

**Comment by lnash94** [comment]
Close this issue with the favour of https://github.com/ballerina-platform/openapi-tools/pull/1616
