### ISSUE TITLE
[Improvement]: Fix issues in Redis Connectors

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#4957]
### Connector Name

module/redis (Redis)

### Suggested improvement

- [x] Identify the gaps in Redis connector
- [x] Fix CI build failure - https://github.com/ballerina-platform/module-ballerinax-redis/pull/181
- [ ] Evaluate on the possibility of implementing a dynamic command invocation 
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/5041
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/4949

### Related issues

https://github.com/ballerina-platform/ballerina-extended-library/issues/32
https://github.com/ballerina-platform/ballerina-standard-library/issues/5041

**Comment by NipunaRanasinghe** [comment]
Closing as completed
