### ISSUE TITLE
[Feature]: Include PATCH document operation to the connector

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-library#4972]
### Connector Name

module/cosmosdb (Cosmos DB)

### Suggested feature

The patch methods are not implemented in the connector, but are available in the CosmosDB API: https://learn.microsoft.com/en-us/rest/api/cosmos-db/patch-a-document. 

The "PATCH" operation allows  to make partial updates to a document by specifying only the fields you want to change, leaving the rest of the document intact. This can be useful when we have a large document and only want to modify a few fields. The "PATCH" operation is also known as the "Partial Update" operation. Implement Patch Document method to include the document patch functionality to the connector

Discord : https://discord.com/channels/957996897782616114/1137459261551689861/1137459261551689861

**Comment by keizer619** [comment]
@ImeshBalasuriya are you still working on this issue?

**Comment by ImeshBalasuriya** [comment]
Hu @keizer619,

Unfortunately, I'm a bit busy atm. If the feature is urgent, please feel free to reassign the issue. If not, I am happy to continue work on it once I am free.

**Comment by Atharva1723** [comment]
Can I work on this issue?

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb/pull/115
