### ISSUE TITLE
[Task]: Implement a test suite for snowflake connector

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-library#4973]
### Connector Name

module/snowflake (SnowFlake)

### Task Description

Need do do the $subject as its required for all the connector modules to have 80+% test coverage and, this is also required to verify the GraalVM compatibility of the connector runtime.

**Comment by keizer619** [comment]
@Harshal0902 Are you working on this issue? If not we can assign this for someone else

**Comment by Harshal0902** [comment]
Hi @keizer619 yes I am working on this issue and I will make a PR soon.

**Comment by daneshk** [comment]
@Harshal0902 Can you update the current status for this issue, please? when can we expect the fix, etc?

**Comment by keizer619** [comment]
@Harshal0902 Are you still working on this?
