### ISSUE TITLE
Upgrade Salesforce connector to new version of salesforce API

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-library#4974]
### Connector Name

module/salesforce (Salesforce)

### Suggested improvement

(Originally reported by @ramith in https://github.com/wso2-enterprise/choreo/issues/22836)

Need to support the latest salesforce API, which is v58. The current Ballerina salesforce connector release supports salesforce v48 API.

**Comment by aashikam** [comment]
This is done with Salesforce 8.0.0 release, hence closing.
