### ISSUE TITLE
[Improvement]: Use GitHub REST APIs Instead of GitHub GraphQL API

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-library#4981]
### Connector Name

module/github (Github)

### Suggested improvement

Currently, the Ballerina GitHub connector is using the GitHub GraphQL API internally to fetch the data. Then the connector exposes the data as REST endpoints for the users. GraphQL and REST represent different paradigms for data fetching. Trying to fit the GraphQL model into the REST paradigm can lead to conceptual mismatches and make the implementation more complex. Also, 
- There are hard-coded GraphQL queries inside the connector implementation to fetch all the fields from GraphQL objects, which beats the purpose of GraphQL APIs. 
- Since GraphQL returns partial data with different errors, error handling gets complex.
- Fetching all the fields from a GraphQL object isn't a good thing as the objects can be large.
- Improvements to the connector can be hard because of the nature of the implementation. There are hard-coded queries with pre-defined query depths, that might not fit all the requirements. If we change the hard-coded queries for other requirements, it will be a breaking change and we will not be able to do patches.
- Users can use the GraphQL generic client and/or generated GraphQL clients for accessing the GraphQL API. Using this would be redundant.

GitHub provides [REST APIs](https://docs.github.com/en/rest?apiVersion=2022-11-28) for all resources accessible via GraphQL. Therefore, Utilizing the REST APIs is preferable over the GraphQL API due to the above reasons.

**Comment by AzeemMuzammil** [comment]
Closing this issue as this is completed.
