### ISSUE TITLE
[Docs]: Add a sample for connecting to a remote mongodb cluster

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-library#4992]
### Connector Name

module/mongodb (Mongo DB)

### Documentation Issue/Improvement

MongoDB Atlas is the prominent remote hosting option for hosting a MongoDB cluster. As I was trying to connect to MongoDB Atlas cluster, I searched for examples where I can have an idea of how to do so. Unfortunately, I could not find any examples.

MongoDB atlas provides connection URLs(strings) for different drivers (java, python, etc). 
![image](https://user-images.githubusercontent.com/35211477/213376692-b8b7a029-f2ea-40f3-9ca3-a99056a2b7c4.png)

I had no clue what driver to select. I randomly selected the `java` driver.  It worked. However, I couldn't find any documentation regarding this. 

It's better if we can add a learn page example or BBE regarding this.

**Comment by ThisaruGuruge** [comment]
This is now implemented and the [API documentation](https://central.ballerina.io/ballerinax/mongodb/latest#setup-guide) includes the information on how to connect to a MonogDB Atlas database.
