### ISSUE TITLE
[Docs]: Update the README.md with the latest cmd changes in Ballerina OpenaAPI tool

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-library#4997]
### Connector Name

connectors/openapi (Open API Connector)

### Documentation Issue/Improvement

The command for generating the Client has been changed to `bal openapi -i openapi.yaml --mode client --client-methods=remote` . As we have mentioned the default command in the doc, it will generate a service instead

References: https://ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.2.0#openapi-tool

### Relevant suggestions

Update the README.md with the new command

**Comment by ThisaruGuruge** [comment]
Closing as this is not valid now.
