### ISSUE TITLE
[Bug]: `Record:IssueComment` is not implemented

### ISSUE THREAD

**Issue by bimsarapathiraja** [ballerina-platform/ballerina-library#5002]
### Connector Name

module/github (Github)

### What happened?

`IssueComment` is not implemented in the ballerina/github even though it is mentioned in the API documentation. `IssueComment[]?` always returns `nil`.

**Comment by AzeemMuzammil** [comment]
Closing this issue as this is no longer valid(The connector is revamped fully)
