### ISSUE TITLE
[Feature]: Add async trigger for `aayu.mftg.as2`

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-library#5007]
### Connector Name

other (None Listed Above)

### Suggested feature

Add async trigger for `aayu.mftg.as2` connector

This is a generated trigger for MFT Gateway (by Aayu Technologies) that allows you to listen to the following events that occur in MFT Gateway. 
- Received Messages
- Sent Messages
- Failed Messages

https://aayutechnologies.com/docs/product/mft-gateway/ 

### Related issues

I am trying to do [...] but [...]

**Comment by NipunaRanasinghe** [comment]
Closing issue, as the mentioned trigger module is available in central prod environment as well 

https://central.ballerina.io/ballerinax/trigger.aayu.mftg.as2/0.9.0
