### ISSUE TITLE
[Improvement]: Use time module API to convert UTC time to email string

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-library#5008]
### Connector Name

module/azure-storageservice (Azure Blob & Storage Service)

### Task Description

Check whether we can use UTC to email string APIs to construct string values [1] in code[2]

1. https://lib.ballerina.io/ballerina/time/2.2.1/functions#utcToEmailString
2. https://github.com/ballerina-platform/module-ballerinax-azure-storage-service/blob/main/storageservice/modules/utils/utils.bal#L25-L39

**Comment by SanduDS** [comment]
This is done
