### ISSUE TITLE
[Bug]: Cannot connect to MongoDB Atlas (cloud offering) using mongodb client

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-library#5013]
### Connector Name

module/mongodb (Mongo DB)

### What happened?

I'm trying to connect to a mongodb atlas database using the mongodb client. First I tried with `sslEnabled: false` as per the examples. Then I got  a connection prematurely closed error when client is initialized. This is probably because the connection is not secure.
```
error: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=cluster0-shard-00-01.1zwpo.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}] {"mongoDBExceptionType":"MongoTimeoutException"}
        at ballerinax.mongodb.3.Client:find(client.bal:131)
           imesha.backend.0.$anonType$_0:$get$customers(main.bal:58)
```

Next, tried with `sslEnabled: true` but then the `secureSocket` is required to be provided. Both trust store and key store are mandatory there. Also the `protocol` field is not documented properly.

### Relevant log output

```shell
See above section
```

**Comment by ThisaruGuruge** [comment]
This is fixed with MongoDB 5.0.0
