### ISSUE TITLE
[Feature]: Choreo samples to demonstrate Kafka Publisher Subscriber model on Choreo

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-library#5015]
### Connector Name

connectors/samples (Connector Samples/Templates)

### Suggested feature

- We need to develop a sample using Kafka to demonstrate the usage of the pub-sub model. 
- This sample needs to be pushed as a template to Ballerina central. 
- This sample should work inside Choreo.

**Comment by ThisaruGuruge** [comment]
Closing the issue as this is no longer a valid issue. Please re-open if needed.
