### ISSUE TITLE
[Improvement]: Implement template "Send scheduled promotional emails via Sendgrid"

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#5022]
### Connector Name

connectors/samples (Connector Samples/Templates)

### Suggested improvement

Implement a template to send promotional emails via Sendgrid using the content in a google sheet

### Related issues

I am trying to do [...] but [...]

**Comment by NipunaRanasinghe** [comment]
Closing as this seems to be related to choreo samples, which is not valid anymore

**Comment by NipunaRanasinghe** [comment]
Closing as this seems to be related to choreo samples, which is not valid anymore
