### ISSUE TITLE
[Feature]: Add Amazon Market Place Connector

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-library#5028]
### Connector Name

other (None Listed Above)

### Suggested feature

Support Amazon Marketplace API though a connector:
link : https://developer.amazonservices.com

### Related issues

I am trying to do [...] but [...]

**Comment by NipunaRanasinghe** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-library/issues/5027
