### ISSUE TITLE
[Docs]: Readme of the extended libraries does not include where to raise issue

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-library#5031]
### Connector Name

other (None Listed Above)

### Documentation Issue/Improvement

README of each extended library does not contain information related to where to raise their issue. Better to add that details to each library. When I first check the Salesforce connector, the issues section is disabled and I couldn’t find where to raise issues.

### Relevant suggestions

Add something like [this](https://github.com/ballerina-platform/module-ballerina-io/blob/master/README.md#issues-and-projects) which follows in standard libraries.

**Comment by ThisaruGuruge** [comment]
Closing since this is now resolved as the Ballerina Library now includes everything.
