### ISSUE TITLE
[Improvement]: MongoDB connector does not support find with skip

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-library#5036]
### Connector Name

module/mongodb (Mongo DB)

### Suggested improvement

In order to support paginated results in a search, skip functionality must be supported.
Please see : https://docs.mongodb.com/manual/reference/method/cursor.skip/

### Related issues

Cannot receive paginated search results.

**Comment by ThisaruGuruge** [comment]
This is now supported with the MongoDB 5.0.0 release. The `find` method accepts [`mongodb:FindOptions`](https://central.ballerina.io/ballerinax/mongodb/latest#FindOptions) record type that includes the `skip` and `limit` fields.
