### ISSUE TITLE
Can we support Redis as a datastore in persist?

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-library#5054]
Redis works as a database, too, hence the request. Please explore.

**Comment by daneshk** [comment]
We are currently doing this as an intern project.

**Comment by dinukaamarasinghe817** [comment]
Intermediate Redis client is almost done. Currently in the process of adding one to one and one to many relationship support.

**Comment by dinukaamarasinghe817** [comment]
This issue is related to closed issue #6015. We need to consider the changes made in #6015 when addressing this open issue.

**Comment by daneshk** [comment]
This is done. Hence closing the issue
