### ISSUE TITLE
Couldn't create a proper client resource function using openAPI

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-library#5058]
**Description:**
Task: https://github.com/ballerina-platform/ballerina-standard-library/issues/4952

Some Microsoft APIs have special charters on the path. Getting the following errors when converting openAPI spec for Microsoft API to client resource function:
- Create duplicate resources as special characters are removed from the resource path.
- Create  invalid substrings
   ```
     string itemPath = itempath.substring(0, itempath.length() - 0);
     string index = itematIndexIndex.substring(0, itematIndexIndex.length() - 0);
    ```
- Treats `int` variable as `string`
   ```
    if !itematIndexIndex.endsWith(")") {
        return error("bad URL");
    }
    ``` 
Using the following spec to reproduce this: 
https://drive.google.com/file/d/1jk2W67ipgkK9dgorLTcw9xHE5uBkcnrK/view?usp=sharing

Output:
<img width="1176" alt="Screenshot 2023-10-18 at 21 31 09" src="https://github.com/ballerina-platform/ballerina-standard-library/assets/12771261/dcd46041-6ec6-4897-b4c2-e8d02c6b6a83">

**Comment by lnash94** [comment]
Could you validate the provided URL `/me/drive/root:/{itemPath}:/workbook/tables/{tableIdOrName}/rows/{rowIndex}`? Is it necessary to include `:` with the path parameters?

If the `:` is indeed required in the URL, it has been concluded during our discussion regarding the specification that remote functions should be generated for the OpenAPI contract. This includes handling complex URLs such as parameterized sub-segments, as discussed here: https://github.com/ballerina-platform/ballerina-spec/issues/1238.

**Comment by kalaiyarasiganeshalingam** [comment]
> Could you validate the provided URL `/me/drive/root:/{itemPath}:/workbook/tables/{tableIdOrName}/rows/{rowIndex}`? 

Yes, This URL is valid.  
API doc for MS: https://learn.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&tabs=http

>Is it necessary to include `:` with the path parameters?

We need to add `:` in the API call path. The API call path is generated correctly when the resource path does not contain the `:`. So, it's not necessary to include `:` with the path parameters.

```ballerina
string resourcePath = string `/me/drive/root:/${getEncodedUri(itemPath)}:/workbookworksheets/${getEncodedUri(worksheetIdOrName)}/tables/${getEncodedUri(tableIdOrName)}/rows/${getEncodedUri(rowIndex)}`;
``` 

Please note that the duplicate resource is created due to other special characters such as `(`, `=`, and `)` missing in the resource path.

OpenAPI spec path:
```
 /me/drive/root:/{itemPath}:/workbook/tables/{tableIdOrName}/rows/itemAt(index={index}):
```

**Expected Ballerina resource path:**
/me/drive/root\:/[string itemPath]/workbook/tables/[string tableIdOrName]/rows/**itemAt(index=[int index])**

**Actual Ballerina resource path:**
/me/drive/root\:/[string itemPath]/workbook/tables/[string tableIdOrName]/rows/**[int itemAtIndexIndex]**

> If the `:` is indeed required in the URL, it has been concluded during our discussion regarding the specification that remote functions should be generated for the OpenAPI contract. This includes handling complex URLs such as parameterized sub-segments, as discussed here: [ballerina-platform/ballerina-spec#1238](https://github.com/ballerina-platform/ballerina-spec/issues/1238).

**Comment by lnash94** [comment]
In that case, we have options
1. If we align with OpenAPI tool code generation, we have decided to generate **remote** functions instead of resource functions for the entire OpenAPI contract in [the previous discussion](https://github.com/ballerina-platform/ballerina-spec/issues/1238#issuecomment-1767582117) for particular scenarios. 
We will work on a fix for the tool to [automatically fallback to generating remote functions](https://github.com/ballerina-platform/ballerina-standard-library/issues/4850#issuecomment-1769882365) if we encounter a URL that cannot be achieved via resource functions 
You can use the following command: `bal openapi -i <yml> --mode client --client-methods remote` till we provide the fix. 

2. If we require resource functions for specific scenarios, we will need to manually write the code to support these URLs.

**Comment by kalaiyarasiganeshalingam** [comment]
@NipunaRanasinghe Shall we go with the remote functions instead of resource functions?

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe Shall we go with the remote functions instead of resource functions?

+1 to proceed with remote method (because of the compilation errors when using the resource function), as per the last discussion we had with the team.
