### ISSUE TITLE
Openapi tool does not escape in built symbols

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#5067]
**Description:**
```yaml
Thread:
      description: A collection of messages representing a conversation.
      properties:
        historyId:
          description: The ID of the last history record that modified this thread.
          format: uint64
          type: string
        id:
          description: The unique ID of the thread.
          type: string
        messages:
          description: The list of messages in the thread.
          items:
            $ref: "#/components/schemas/Message"
          type: array
        snippet:
          description: A short part of the message text.
          type: string
      type: object
```

Thread schema will result in a record of name Thread. Here thread is ballerina key symbol.

<img width="727" alt="Screenshot 2023-10-22 at 12 38 45" src="https://github.com/ballerina-platform/ballerina-standard-library/assets/27669465/f60328ea-9de9-4b01-9bdb-23df05c16719">

**Comment by lnash94** [comment]
This is the know issue from the ballerina lang: https://github.com/ballerina-platform/openapi-tools/issues/479

**Comment by niveathika** [comment]
To further give context, `Thread` is not a keyword but a revered word i.e for the implementation  this is needed. However there is no way to solve except to rename the variable. This will be a huge task.

**Comment by lnash94** [comment]
Close this issue with the approval of this https://github.com/ballerina-platform/ballerina-lang/issues/22851.
