### ISSUE TITLE
Support response schema name with numbers in Service generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#5108]
**Description:**
Found a scenario where the schema name is a number. Ex: `200`

```yaml
responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
```
This a valid OpenAPI spec use case. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dilanSachi** [comment]
This is fixed with new restructure - https://github.com/ballerina-platform/openapi-tools/pull/1668
