### ISSUE TITLE
Remove the duplicated openapi-validator jar in distribution

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-library#5115]
**Description:**
Openapi-validator jar is packed in both distribution and the BCentral available package. This is currently used as a package provided compiler plugin. We need to check whether this can be removed from the distribution.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
The one packed with the package is not required, we only need it in the compiler plugin. So removed it in here: https://github.com/ballerina-platform/openapi-tools/pull/1752
