### ISSUE TITLE
Provide support for generic intersection types

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#5124]
**Description:**

With the plan to support generic media types in U8 (https://github.com/ballerina-platform/ballerina-lang/issues/24078) the Ballerina to OpenAPI schema should be updated accordingly. Otherwise the spec generated for the intersection types would be invalid. 

The implementation might be blocked from the bug https://github.com/ballerina-platform/ballerina-lang/issues/41061

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
This was tested on the Ballerina 2201.10.0 and this was fixed via the revamping
