### ISSUE TITLE
Invalid resource path generated for paths with extension 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#5144]
**Description:**
$subject 
Affected connectors : [adp.paystatements](https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/adp.paystatements), [nytimes.topstories](https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/nytimes.topstories)

### Sample OpenAPI resource
```yaml
 /payroll/v1/workers/{associateoid}/organizational-pay-statements/{payStatementId}/images/{imageId}.{imageExtension}:
    get:
      summary: Request the details of a specific paystatement as an image.
      operationId: getClientPayStatementImage
      parameters:
        - $ref: "#/components/parameters/associateoid"
        - $ref: "#/components/parameters/payStatementId"
        - $ref: "#/components/parameters/imageId"
        - $ref: "#/components/parameters/imageExtension"
        - $ref: "#/components/parameters/roleCode"
        - $ref: "#/components/parameters/if-none-match"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: Pay statement image
```

### Generated resource function 

```bal
    resource isolated function get payroll/v1/workers/[string associateoid]/'organizational\-pay\-statements/[string payStatementId]/images/[string imageidImageextension](string roleCode, string? ifNoneMatch = ()) returns json|error {
        if !imageidImageextension.endsWith(".{imageExtension}") {
            return error("bad URL");
        }
        string imageId = imageidImageextension.substring(0, imageidImageextension.length() - 16);
        string resourcePath = string `/payroll/v1/workers/${getEncodedUri(associateoid)}/organizational-pay-statements/${getEncodedUri(payStatementId)}/images/${getEncodedUri(imageId)}.${getEncodedUri(imageExtension)}`;
        map<any> headerValues = {"roleCode": roleCode, "If-None-Match": ifNoneMatch};
        map<string|string[]> httpHeaders = getMapForHeaders(headerValues);
        json response = check self.clientEp->get(resourcePath, httpHeaders);
        return response;
    }
```

Gives the below compiler error
`ERROR [client.bal:(132:202,132:216)] undefined symbol 'imageExtension'

**Steps to reproduce:**
1. Find the sample OpenAPI file [here](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/adp.paystatements/openapi.yml)
2. Run `bal openapi -i <openapi-file> --mode client

**Affected Versions:**
2201.4.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
If there is a path with the parameterized path segments those API needs to be generated with the **remote** functions. Therefore this issue is closed in favour of this discussion https://github.com/ballerina-platform/ballerina-spec/issues/1238#issuecomment-1767582117
