### ISSUE TITLE
Add test cases to validate formatting in client generations

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#5164]
**Description:**
$subject

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
The current tool implementation is based on the lang formatted API. Therefore we will close this issue since some formatted cod comparison has intermittent test failures due to the depending on the env, system environment
