### ISSUE TITLE
Improve swagger export to include HTML and documentation

### ISSUE THREAD

**Issue by autodidaddict** [ballerina-platform/ballerina-library#5176]
**Description:**
I have been able to use `ballerina swagger export` to produce OpenAPI 3.x yaml files and that seems fine. However, I can't find a single open source product capable of reading that file and producing static HTML documentation, which is often a requirement for enterprises deploying large numbers of services.

I would like to be able to have the option of producing static HTML that matches the swagger view from composer as static HTML. This way, I don't have to spend days/weeks hunting down the one obscure Swagger-to-HTML tool that can handle the OpenAPI file produced by Ballerina.. it should "just work", e.g. `ballerina swagger export -l html foo/service.bal`

Additionally - it doesn't look like any of the documentation I'm adding to the service or resources is making it into the Swagger. This should definitely show up in the output. If some of this is aided with the `@swagger:Foo` annotations, then documentation should be provided because there's no information on going from Ballerina to swagger to HTML.

**Steps to reproduce:**

`ballerina swagger export foo/service.bal`

**Affected Versions:**

0.980.1

**Suggested Labels (optional):**
enhancement

**Comment by lnash94** [comment]
We are now (Balllerina 2201.10.0 version) capable of exporting swagger UI into HTML by providing `@openapi:ServiceInfo`  annotation with an `embed` field. more info https://blog.ballerina.io/posts/2024-08-23-announcing-ballerina-2201.10.0-swan-lake-update-10/#:~:text=A%20contract%2Dfirst,maintainable%20code%20base.
