### ISSUE TITLE
[websubhub] Retry sending events to subscriber when subscriber sends 5** error code

### ISSUE THREAD

**Issue by janethavi** [ballerina-platform/ballerina-library#5719]
**Description:**
The Choreo audit logging component uses websubhub. When events are continuously sent to the audit logging component from websubhub, sometimes the audit logging component returns a `5**` status code to the websubhub side. Then immediately websubhub stops sending the events to the audit logging component. From the audit logging component side, the pods are still in a running state. Hence automatic resubscription should happen and start sending the events back again to the audit logging component. This is the expected behavior. 

But truly the automatic subscription does not happen and the resubscription happens when the audit-logging deployment is restarted. This is a management overhead for the SRE team and this happens several times per month in production and in stage environment. 

This issue is created as a problem task for an incident in the production environment. Please find the RCA of the incident underneath
https://docs.google.com/document/d/1anB-Py_fyofUSgChEEPHNXolltDc_scRdR4Hc2Vt6GU/edit?usp=sharing

**Comment by chirangaalwis** [comment]
ServiceNow Problem task ID: `PRB0040878`
