### ISSUE TITLE
Remove unused generated records from `types.bal` low resource service binding  

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#5731]
**Description:**
$Subject

**Comment by rashm1n** [comment]
Related issue
* https://github.com/wso2-enterprise/internal-support-ballerina/issues/484

Improvement
Removal of unnecessary records in `types.bal` file and prevent it from generating if the file is empty

**Comment by lnash94** [comment]
With this fix https://github.com/ballerina-platform/openapi-tools/pull/1578, If a cyclic array[1] is not used, it won't be removed from types.bal due to this issue https://github.com/ballerina-platform/ballerina-lang/issues/36442
[1]
```ballerina
type JToken JToken[]
```
