### ISSUE TITLE
Failing templated workflows

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#5769]
**Description:**
$subject
1. Connector Graalvm build
2. Pusblish to dev/staging central

Both workflows are failing due to 
<img width="1319" alt="Screenshot 2023-11-14 at 17 06 23" src="https://github.com/ballerina-platform/ballerina-library/assets/27669465/e08beec0-ab3f-4e65-b540-a1356c4f3846">

Full Log: https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail/actions/runs/6862315218/job/18659761693

Looking into it I found out target directory is created with `root` user permission.

**Comment by DimuthuMadushan** [comment]
Maybe due to the https://github.com/ballerina-platform/plugin-gradle/issues/114. @MohamedSabthar has fixed this with gradle plugin version `2.1.6`. Can you try updating the gradle plugin version?

**Comment by niveathika** [comment]
Its already updated.
