### ISSUE TITLE
Allow additional release flags `release-package-connector-template` workflow

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-library#5797]
**Description:**
At the moment, we are not allowed to pass any additional release flags, and there are special case requirements where we have to skip tests in the release workflow. (ie: we don't have API keys to use in GitHub workflows as the keys we are using to test locally are customer owned.). If there is a way we can pass release flags as well, we can skip tests in this case.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Ideally, we shouldn't allow releasing packages without running tests. Having said that, the Candid connector is a special case. To allow these special cases, this [PR](https://github.com/ballerina-platform/ballerina-library/pull/5798)  allows passing additional flags to release task. 

The ideal solution would be to find a way to run tests, (maybe by mocking, or getting a key), or else, by disabling the tests from the Gradle scripts. (This discourages passing additional flags to disable tests while releasing). But until we find a proper solution, +1 to allow passing additional flags, and disabling them at the workflow level.

**Comment by ThisaruGuruge** [comment]
Closing as this is now fixed.
