### ISSUE TITLE
Avoiding anti-patterns in OpenAPI code generation

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-library#5812]
**Description:**
When the OpenAPI tool is used to generate client APIs for Google Calendar, some anti-patterns can be observed in the generated code.

1. Having parentheses in `if` conditions

  ```ballerina
    if (value is SimpleBasicType) {
        recordArray.push(key, "=", getEncodedUri(value.toString()));
    } else if (value is SimpleBasicType[]) {
        recordArray.push(getSerializedArray(key, value, explode = explode));
    } else if (value is record {}) {
        recordArray.push(getFormStyleRequest(parent, value, explode));
    }
  ```
2. Incorrect formatting for `enum`
  ```ballerina
    enum EncodingStyle {
        DEEPOBJECT, FORM, SPACEDELIMITED, PIPEDELIMITED
    }
  ```

**Steps to reproduce:**

- Download the [Google Calendar OAS](https://github.com/APIs-guru/openapi-directory/blob/main/APIs/googleapis.com/calendar/v3/openapi.yaml) file to a local directory

- Execute the following command
`bal openapi -i openapi.yaml --mode client --client-methods resource`

- Find the anti-patterns in the `utils.bal` file

**Comment by lnash94** [comment]
2. 
```
enum EncodingStyle {
      DEEPOBJECT, FORM, SPACEDELIMITED, PIPEDELIMITED
  }
```
The ballerina formatter doesn't format this properly.
