### ISSUE TITLE
Signing and verifying using the algorithm SHA384withECDSA in the ballerina/crypto module 

### ISSUE THREAD

**Issue by NirashaSewwandi** [ballerina-platform/ballerina-library#5821]
**Description:**
>**ballerina/crypto** module has signing and verifying options for signature algorithm **RSA**.
Need to add the signing and verification for the **SHA384withECDSA** algorithm as well.

**Comment by anuruddhal** [comment]
Our feature is stuck due to this. 
Is this a hard fix? Can we please get an ETA?
