### ISSUE TITLE
[Bug]: Deprecated notation does not work correctly with resource functions

### ISSUE THREAD

**Issue by chalindukodikara** [ballerina-platform/ballerina-library#5831]
### Description

The deprecated notation produces an error for a resource function. Ballerina version = 2201.8.0

![image](https://github.com/ballerina-platform/ballerina-lang/assets/38396435/0b45342e-9d27-4186-9594-16fceb31d4d3)

![image](https://github.com/ballerina-platform/ballerina-lang/assets/38396435/f5cd6c23-4cda-4ce6-a173-16ded20302f7)

### Steps to Reproduce

Repository where the error occurred.
https://github.com/wso2-enterprise/choreo-cp-configuration-service

### Related area

-> Compilation

### Suggested label(s) (optional)

Team/CompilerFE

**Comment by nipunayf** [comment]
The above problem can be reproduced with the following simple code. 

```ballerina
import ballerina/http;

service on new http:Listener(8080) {

    @deprecated
    resource function accessor path() {
        
    }
}
```

It generates the error `invalid resource method annotation type: expected http:ResourceConfig, but found deprecated` for the `ballerina/http`, and the error is specific to this module. The error cannot be reproduced with the `ballerina/udp` module.
