### ISSUE TITLE
Dependency conflict in "ballerina/persist.sql" module

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-library#5869]
**Description:**
Unexpected warning when using `mysql` data source with bal persist.

**Steps to reproduce:**
- Create a new package with Ballerina Swan Lake Update 8 Patch 4
- Use `bal persist init --datastore mysql` to initialize the persist config
- Write a simple data model and use `bal persist generate` to generate the client class. 
- Use `bal build`, and you should see the following warning

```
ING [foo] detected conflicting jar files. 'persist.sql-native-1.2.1.jar' dependency of 'ballerinax/persist.sql' conflicts with 'persist.sql-native-1.2.0.jar' dependency of 'sameera/foo'. Picking 'persist.sql-native-1.2.1.jar' over 'persist.sql-native-1.2.0.jar'.
```

Here is my `Ballerina.toml`
```
[persist]
datastore = "MySQL"
module = "foo"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"

``` 

**Affected Versions:**
Ballerina 2201.8.4 (Swan Lake Update 8)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
This is due to the latest `persist-sql` native jar not syncing with Maven Central probably. For now, we will remove the latest version `1.2.1` from Ballerina Central. We are going to allow resolving native jars from the wso2 nexus repo from update 09 onwards. It will not happen in the future.

**Comment by sameerajayasoma** [comment]
This can be a problem for people who have already installed 1.2.1 right? Removing a version can be tricky. How about introducing a new version like 1.2.2

**Comment by daneshk** [comment]
I will ask them to sync the 1.2.1 version with Maven Central.

**Comment by daneshk** [comment]
From update 09, external jars are resolved from the WSO2 nexus. So we don't need to wait till it syncs to maven central. Hence closing this issue.
