### ISSUE TITLE
[Bug]: The GitHub std.lib level 7 build fails due to a test failure in the SQL compiler plugin

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-library#5872]
**Description:**
As logged in [here](https://github.com/ballerina-platform/ballerina-lang/actions/runs/7163845727/job/19503014823?pr=41773), many of the recent PRs are failing due to a test failure in the SQL compiler plugin. It logs the error message:

```
SQL compiler plugin test suite > SQL Compiler Plugin Tests > io.ballerina.stdlib.sql.compiler.CompilerPluginTest > testInvalidConnectionParamConfig FAILED
    java.lang.AssertionError at CompilerPluginTest.java:70
```

**Comment by niveathika** [comment]
@nipunayf This is not reproducible locally with latest master commit. Shsll we update the base in the PR and try?

**Comment by niveathika** [comment]
The root cause of the issue seems to be https://github.com/ballerina-platform/ballerina-lang/issues/41866

We will currently disable all testcases to proceed
