### ISSUE TITLE
Incorrect formatting for deprecated elements

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-library#5881]
$subject 

E.g. https://central.ballerina.io/ballerinax/googleapis.sheets/3.5.0#Client-appendRowToSheet

<img width="1463" alt="image" src="https://github.com/ballerina-platform/ballerina-central/assets/16300038/aa73e299-2bd9-4ff2-a364-6c35e3922a7f">

**Comment by ThisaruGuruge** [comment]
How does this happen from Package.md file? These are generated API doc, right?

**Comment by sm1990** [comment]
> How does this happen from Package.md file? These are generated API doc, right?

Sorry, my bad. It's not the package.md, it's coming from the annotations in the bal file.

**Comment by ThisaruGuruge** [comment]
> Sorry, my bad. It's not the package.md, it's coming from the annotations in the bal file.

So what is the exact issue here? How can we avoid this?

**Comment by sm1990** [comment]
> > Sorry, my bad. It's not the package.md, it's coming from the annotations in the bal file.
> 
> So what is the exact issue here? How can we avoid this?

The issue occurs in https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/66907fec1ce68a47e8fa08733dbb8e0918abae0b/ballerina/client.bal#L1142. We have used `#` which denotes a `H1` tag in markdown. 

The solution:-
**Option 1**
We can use `######` and covert it to a H6 tag.
 
![image](https://github.com/ballerina-platform/ballerina-library/assets/7709843/f39d56b4-c30a-45b8-8b4c-8a3a94462d63)

**Option 2**
Remove the text as we already have the `Depreciated` label unless there is a message following it.

**Option 3**
Move the message to top (before the method signature) and show it as a `blockquote`.
![image](https://github.com/ballerina-platform/ballerina-library/assets/7709843/82acb1db-c9b0-49f0-a371-2217b47e724f)

I personally prefer Option 3 as I think the uses should see the depreciation message right away.

**Comment by ThisaruGuruge** [comment]
These options should not solve the issue since this is how we write doc comments for deprecated items. I think this should be handled from the doc generation side.

@hasithaa any thoughts?

**Comment by hasithaa** [comment]
@ThisaruGuruge I agree. I had a chat offline chat with @sm1990 and discussed a possible UX. The idea is to limit the markdown heading based on the context.

**Comment by sm1990** [comment]
Adding @NipunaMadhushan

**Comment by NipunaMadhushan** [comment]
This issue will be tracked with https://github.com/ballerina-platform/ballerina-lang/issues/41928.

**Comment by sm1990** [comment]
The fix will be available with update 9.

**Comment by sm1990** [comment]
The issue is fixed. The change will be visible from the next version of the connector.
