### ISSUE TITLE
Develop Specifications for Ballerina EDI Module and EDI Schema

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-library#5920]
**Description:**
As part of enhancing the Ballerina language's capabilities for handling Electronic Data Interchange (EDI), we propose the development of a standard specification for Ballerina EDI schema and Ballerina EDI module. This specifications aims to provide a structured and standardized way for representing EDI data within the Ballerina programming language.

**Describe your problem(s):**
Currently, Ballerina lacks a standardized schema specification/module specification for handling Electronic Data Interchange, which makes it challenging for developers to work seamlessly with EDI data. The absence of a standard specifications hinders interoperability and may result in inconsistencies when exchanging EDI messages between different systems.

**Describe your solution(s):**
The proposed solution is to develop a standard specifications for Ballerina EDI schema and Ballerina EDI module. This  Ballerina EDI schema specification should define a consistent and expressive syntax for representing various EDI formats within Ballerina, enabling developers to easily work with and manipulate EDI data. Additionally, the Ballerina EDI module specification should address common use cases and provide clear guidelines on how to use module/edi.

**Comment by RDPerera** [comment]
# Ballerina EDI Schema Specification [DRAFT]

## Introduction
Ballerina facilitates seamless handling of EDI (Electronic Data Interchange) data by converting it into Ballerina records. To define the structure of EDI data, developers can utilize the Ballerina EDI Schema Specification. This specification outlines the essential elements needed to describe an EDI schema, including the name, delimiters, segments, segment groups, field definitions, components, and additional configuration options.

## Specification

### 1. Name
The `name` field specifies the name of the EDI schema.

### 2. Delimiters
The `delimiters` field defines the delimiters used in the EDI data. It includes the following subfields:
   - **segment:** The delimiter used to separate segments.
   - **field:** The delimiter used to separate fields within a segment.
   - **component:** The delimiter used to separate components within a field.
   - **repetition:** The delimiter used to indicate repetition of a field or component.

**Example:**
```json
"delimiters": {
    "segment": "~",
    "field": "*",
    "component": ":",
    "repetition": "^"
}
```

### 3. Segments
The `segments` field is an array of segment definitions. Each segment definition includes the following subfields:
   - **code:** The code representing the segment.
   - **tag:** A user-friendly tag or name for the segment.
   - **minOccurances:** The minimum number of times the segment must occur.
   - **maxOccurances:** The maximum number of times the segment can occur (-1 indicates unlimited occurrences).
   - **fields:** An array of field definitions within the segment.

**Example:**
```json
"segments": [
    {
        "code": "HDR",
        "tag": "header",
        "minOccurances": 1,
        "maxOccurances": 1,
        "fields": [
            {"tag": "code", "required": true},
            {"tag": "orderId", "required": true},
            {"tag": "organization"},
            {"tag": "date"}
        ]
    },
    {
        "code": "ITM",
        "tag": "items",
        "minOccurances": 0,
        "maxOccurances": -1,
        "fields": [
            {"tag": "code", "required": true},
            {"tag": "item", "required": true},
            {"tag": "quantity", "required": true, "dataType": "int"}
        ]
    }
]
```

### 4. Sub-definitions of Segments
For each segment, the following sub-definitions are provided:
   - **code:** The code representing the segment.
   - **tag:** A user-friendly tag or name for the segment.
   - **minOccurances:** The minimum number of times the segment must occur.
   - **maxOccurances:** The maximum number of times the segment can occur (-1 indicates unlimited occurrences).
   - **fields:** An array of field definitions within the segment.

### 5. Definition for Fields

Within the `fields` sub-definition, the `length` attribute is used to specify the length constraints for a field. This object includes parameters for fixed length, minimum length, and maximum length, offering comprehensive control over the size of the field.

- **tag:** A user-friendly tag or name for the field.
- **repeat:** Indicates whether the field can be repeated.
- **required:** Indicates whether the field is required.
- **dataType:** The data type of the field.
- **startIndex:** The starting index of the field within the segment.
- **length:** An object specifying length constraints for the field.

#### Type Constraints

The `dataType` parameter accepts the following types:

- **STRING:**
  - Denoted by the value "string," it signifies that the field should contain textual data.

- **INT:**
  - Denoted by the value "int," it indicates that the field should contain integer numeric data.

- **FLOAT:**
  - Denoted by the value "float," it signifies that the field should contain floating-point numeric data.

- **COMPOSITE:**
  - Denoted by the value "composite," it represents a component group within the field. A composite field may contain multiple sub-components, providing a structured way to organize complex data.

#### Example Usage
```json
"fields": [
    {"tag": "CustomerName", "dataType": "string", "length": 50},
    {"tag": "Quantity", "dataType": "int", "length": {"min": 1}},
    {"tag": "Price", "dataType": "float", "length": {"max": 10}},
    {"tag": "Address", "dataType": "composite", "components": [
              {
                "tag": "No",
                "required": false,
                "dataType": "string"
              },
              {
                "tag": "Street",
                "required": false,
                "dataType": "string"
              },
              {
                "tag": "City",
                "required": false,
                "dataType": "string"
              }
            ]}
]
```

#### Length Constraints

The `length` object provides the following constraints:

- **Fixed-Length:**
  - If `fixed-length` is specified as `N` and the field's actual length is equal to `N`, Ballerina retains the field as is.
  - If the actual length is less than `N`, Ballerina pads the field with spaces until it fulfills the fixed length.
  - If the actual length exceeds `N`, an error is produced.

- **Minimum Length:**
  - Specifies the minimum length of the field.
  - If the length is below the specified minimum, an error is produced.

- **Maximum Length:**
  - Specifies the maximum length of the field.
  - If the length exceeds the specified maximum, an error is produced.

#### Example Usage
```json
"fields": [
    {"tag": "DocumentNameCode", "length": 10},
    {"tag": "DocumentNumber", "length": {"min": 1}},
    {"tag": "MessageFunction", "length": {"max": 3}},
    {"tag": "ResponseType", "length": {"min": 1, "max": 3}}
]
```

### 6. Definition for Components
For each component within a field, the following sub-definitions are provided:
   - **tag:** A user-friendly tag or name for the component.
   - **required:** Indicates whether the field is required.
   - **dataType:** The data type of the component.
#### Example Usage
```json
"code": "ORG",
            "tag" : "organization",
            "fields" : [
                {"tag" : "code"}, 
                {"tag" : "partnerCode"}, 
                {"tag" : "name"}, 
                {"tag" : "address", "components" : [
                            {"tag" : "streetAddress"}, 
                            {"tag" : "city"}, 
                            {"tag" : "country"}
                ]}, 
                {"tag" : "contact", "repeat" : true}]
```
### 7. Definition for Sub-components 
For each sub-component within a component, the following sub-definitions are provided:
   - **tag:** A user-friendly tag or name for the sub-component.
   - **required:** Indicates whether the field is required.
   - **dataType:** The data type of the sub-component.
#### Example Usage
```json        
            "code": "ORG",
            "tag" : "organization",
            "fields" : [
                {"tag" : "code"},
                {"tag" : "partnerCode"}, 
                {"tag" : "name"}, 
                {"tag" : "contact", "components" : [
                    {"tag": "mobile"},
                    {"tag": "fixedLine"},
                    {"tag" : "address", "subcomponents" : [
                        {"tag" : "streetAddress"}, {"tag" : "city"}, {"tag" : "country"}]}     
                ]}]
```
### 8. Additional Configuration (Optional)
   - **ignoreSegments:** An array of segments to be ignored during processing.
   - **preserveEmptyFields:** Indicates whether empty fields should be preserved.
   - **includeSegmentCode:** Indicates whether the segment code should be included in the Ballerina record.

**Comment by RDPerera** [comment]
@chathurace @niveathika  I've created a draft specification for Ballerina EDI Schema in 🔝. Check it out and let me know your thoughts. 😃

**Comment by RDPerera** [comment]
# Specification: Ballerina EDI Module [DARFT]

_Owners_: @sample_user
_Reviewers_: @sample_user
_Created_: 2024/01/19
_Updated_: 2024/01/19
_Edition_: Swan Lake

## Introduction

This is the specification for the `edi` module of the [Ballerina language](https://ballerina.io). The `edi` module provides functionality to convert EDI text to JSON and JSON to EDI text. Additionally, it supports defining the schema of EDI files in JSON format. The module includes three functions: `fromEdiString`, `toEdiString` and `getSchema`.

If you have any feedback or suggestions about the module, start a discussion via a [GitHub issue](https://github.com/ballerina-platform/ballerina-standard-library/issues) or in the [Discord server](https://discord.gg/ballerinalang). Based on the outcome of the discussion, the specification and implementation can be updated. Community feedback is always welcome. Any accepted proposal, which affects the specification, is stored under `/docs/proposals`. Proposals under discussion can be found with the label `type/proposal` on GitHub.

## Contents

1. [Overview](#1-overview)
2. [Functions](#2-functions)
    * 2.1 [`getSchema` function](#21-getschema-function)
    * 2.2 [`fromEdiString` function](#22-fromedistring-function)
    * 2.3 [`toEdiString` function](#23-toedistring-function)
3. [`EdiSchema` Record](#3-edischema-record)

## 1. Overview

The Ballerina language offers first-class support for handling network-structured data, and the `edi` module leverages these features to facilitate the conversion between EDI text and JSON, with the ability to define the EDI schema in JSON format.

## 2. Functions

This section outlines the functions provided by the Ballerina `edi` module.

### 2.1 `getSchema` function

Creates an EDI schema from a string or a JSON.

```ballerina
function getSchema(string|json schema) returns EdiSchema|error
```

#### Parameters
- `schema` string|json - Schema of the EDI type.

#### Return Type
- `EdiSchema|error` - Error is returned if the given schema is not valid.

#### Example
The following is a basic EDI schema, assuming it is stored in the `edi-schema.json` file:

```json
{
    "name": "SimpleOrder",
    "delimiters" : {"segment" : "~", "field" : "*", "component": ":", "repetition": "^"},
    "segments" : [
        {
            "code": "HDR",
            "tag" : "header",
            "fields" : [{"tag": "code"}, {"tag" : "orderId"}, {"tag" : "organization"}, {"tag" : "date"}]
        },
        {
            "code": "ITM",
            "tag" : "items",
            "maxOccurances" : -1,
            "fields" : [{"tag": "code"}, {"tag" : "item"}, {"tag" : "quantity", "dataType" : "int"}]
        }
    ]
}
```

Below code reads the edi-schema.json file and assign to a edi:EdiSchema variable which holds Ballerina EDI Schema.

```ballerina
import ballerina/io;
import balarina/edi;

public function main() returns error? {
    edi:EdiSchema schema = check edi:getSchema(check io:fileReadJson("resources/edi-schema.json"));
    io:println(schema.toString());
}
```

### 2.2 `fromEdiString` function

Reads the given EDI text according to the provided schema.

```ballerina
function fromEdiString(string ediText, EdiSchema schema) returns json|Error
```

#### Parameters
- `ediText` string - EDI text to be read.
- `schema` EdiSchema - Schema of the EDI text.

#### Return Type
- `json|Error` - JSON variable containing EDI data. Error if the reading fails.


#### Example

Below code reads the `edi-sample.edi` into a json variable named "orderData".
_(given schema is based on the schema used in the above example)_

```ballerina
import ballerina/io;
import balarina/edi;

public function main() returns error? {
    edi:EdiSchema schema = check edi:getSchema(check io:fileReadJson("resources/edi-schema.json"));
    string ediText = check io:fileReadString("resources/edi-sample.edi");
    json orderData = check edi:fromEdiString(ediText, schema);
    io:println(orderData.toJsonString());
}
```

### 2.3 `toEdiString` function

Writes the given JSON variable into EDI text according to the provided schema.


```ballerina
function toEdiString(json msg, EdiSchema schema) returns string|Error
```

#### Parameters
- `msg` json - JSON value to be written into EDI.
- `schema` EdiSchema - Schema of the EDI text.

#### Return Type
- `string|Error` - EDI text containing the data provided in the JSON variable. Error if the writing fails.

#### Example

Below code converts of a json data to EDI text :
_(given schema is based on the schema used in the above example)_

```ballerina
import ballerina/io;
import balarinax/edi;

public function main() returns error? {
    json order2 = {...};
    edi:EdiSchema schema = check edi:getSchema(check io:fileReadJson("resources/edi-schema.json"));
    string orderEDI = check edi:toEdiString(order2, schema);
    io:println(orderEDI);
}
```

## 3. `EdiSchema` Record

The `EdiSchema` record represents the schema of the EDI text. To define the structure of EDI data, developers can utilize the [Ballerina EDI Schema Specification](link).

**Comment by RDPerera** [comment]
@chathurace @niveathika I've created a darf specification for the Ballerina EDI Module as well. Feel free to review it too and share your thoughts. 😃

**Comment by niveathika** [comment]
@RDPerera This LGTM. I have made minor suggestions to language in https://github.com/ballerina-platform/module-ballerina-edi/pull/31

**Comment by RDPerera** [comment]
As it's completed and approved.
