### ISSUE TITLE
Add `Jsonpath` support for Ballerina json module

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-library#5938]
Currently [JsonPath](https://docs.oracle.com/cd/E60058_01/PDF/8.0.8.x/8.0.8.0.0/PMF_HTML/index.htm#t=JsonPath_Expressions.htm) is not supported for Ballerina json types.
The aim of this task is to introduce the Jsonpath support for Ballerina Json type.

> Sub tasks

- [x] Integrate with Java existing [JsonPath library](https://github.com/json-path/JsonPath) library by converting to string (Will refer as Jayway Implementation in the future comments)
- [x] Integrate with Java existing [JsonPath library](https://github.com/json-path/JsonPath) library by imlementing SPIs. ( WIll refer as SPI Implementation in future comments)
- [x] Optimize the SPI implementation
- [x] Load Test the implementations
- [x] Add unit tests

**Comment by SasinduDilshara** [comment]
Currently working on the third subtask.

I compared the output module of the first task and the second task.
When the complexity of the jsonpath syntax get increased the second approach become slow.
But the second method is fast for the simple jsonpaths

Currently working a way to optimize

**Comment by SasinduDilshara** [comment]
> Currently working on the third subtask.
> 
> I compared the output module of the first task and the second task. When the complexity of the jsonpath syntax get increased the second approach become slow. But the second method is fast for the simple jsonpaths
> 
> Currently working a way to optimize

The reason for this performance issue is, `com.jayway.jsonpath` library use `toString()` method inside their function calls.
So currently, the `toString` runtime implementation for Ballerina maps are 10x slow than the Java json `toString` implementation.

**Comment by SasinduDilshara** [comment]
> > Currently working on the third subtask.
> > I compared the output module of the first task and the second task. When the complexity of the jsonpath syntax get increased the second approach become slow. But the second method is fast for the simple jsonpaths
> > Currently working a way to optimize
> 
> The reason for this performance issue is, `com.jayway.jsonpath` library use `toString()` method inside their function calls. So currently, the `toString` runtime implementation for Ballerina maps is 10x slow than the Java json `toString` implementation.

But if we consider some basic queries and popular queries, the second implementation shows good performance.

**Comment by SasinduDilshara** [comment]
While doing the fourth subtask, blocker was found
https://github.com/ballerina-platform/ballerina-library/issues/5958

**Comment by SasinduDilshara** [comment]
> While doing the fourth subtask, blocker was found #5958

Found a workaround for the blocker, currently doing the load testing.

**Comment by SasinduDilshara** [comment]
The load test results for the SPI implementation and the jayway implementation

https://docs.google.com/spreadsheets/d/1wvb6a11Oh7oZkjKAkEeDU9pFpmrCFVpsNyTQu5_-pHk/edit?usp=sharing

According to this the average response time and the throughput of the SPI implementation is better in below ways.
    1 Thread - 19% better
    2 Thread - 29%
    5 Thread - 44%
    10 Thread - 25%
    
 I used `$.store.book[*].price` as the jsonpath expression.

**Comment by SasinduDilshara** [comment]
Important to note that, SPI implementation is 20% slower for jsonpath expressions like `$..price.avg()`. But this notation is not very much common. For common expressions like field accessing arrays and comparing expressions SPI implementation shows better performance(as mention in the above comment).

**Comment by prakanth97** [comment]
> https://docs.google.com/spreadsheets/d/1wvb6a11Oh7oZkjKAkEeDU9pFpmrCFVpsNyTQu5_-pHk/edit?usp=sharing

A small suggestion, instead of sharing the google doc link which is restricted to few people, shall we add screen shot or doc link that can be accessed by everyone?

**Comment by SasinduDilshara** [comment]
> > https://docs.google.com/spreadsheets/d/1wvb6a11Oh7oZkjKAkEeDU9pFpmrCFVpsNyTQu5_-pHk/edit?usp=sharing
> 
> A small suggestion, instead of sharing the google doc link which is restricted to few people, shall we add screenshot or doc link that can be accessed by everyone?

+1, will share a public doc

**Comment by SasinduDilshara** [comment]
PR for the implementation

https://github.com/ballerina-platform/module-ballerina-data.jsondata/pull/1

**Comment by SasinduDilshara** [comment]
Issue found for the `concat` operations of JsonPath expressions in the library.
Reported in here https://github.com/ballerina-platform/ballerina-lang/issues/42064
