### ISSUE TITLE
GraphQL Listener is not allowing `Content-type: application/json;charset=UTF-8` header

### ISSUE THREAD

**Issue by yashodgayashan** [ballerina-platform/ballerina-library#5945]
**Description:**

I have a GraphQL component and when I call the server with `Content-type: application/json;charset=UTF-8` it says invalid content type. When I try with the HTTP library it works fine.

**Steps to reproduce:**

1. Create a graphql service - https://ballerina.io/learn/write-a-graphql-api-with-ballerina/
2. Run it with `bal run`
3. curl `curl --location 'http://localhost:9000/covid19' \
--header 'Content-type: application/json;charset=UTF-8' \
--header 'scope: unknown' \
--data '{"query":"query { all { country cases active} }","variables":{}}'`

Please note when I use the HTTP library and invoke it with the same header it worked. 
- example I used - https://ballerina.io/learn/by-example/http-basic-rest-service/
- curl `curl --location 'http://localhost:9090/albums' \
--header 'Content-Type: application/json;charset=UTF-8'`

**Affected Versions:**

2201.8.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
This is the expected behaviour according to the [GraphQL over HTTP](https://graphql.github.io/graphql-over-http/draft/#sec-Media-Types) spec. A GraphQL server assumes UTF-8 encoding by default and does not need to provide the encoding with the content-type header.

**Comment by ThisaruGuruge** [comment]
Closing as per the above comment, please re-open if needed.
