### ISSUE TITLE
Proposal: Mapping Interceptor Responses into Generated OpenAPI Specification

### ISSUE THREAD

**Issue by SachinAkash01** [ballerina-platform/ballerina-library#5956]
## Summary
Implement the feature to incorporate interceptor responses into the generated OpenAPI specification for HTTP services.

## Goals
- Improve the Ballerina OpenAPI tool to support interceptor response mapping into the generated OpenAPI specification.

## Motivation

OpenAPI is a widely used standard for documenting APIs. It allows developers to specify the structure and data types expected in API requests and responses. One of its valuable features is built-in schema validation, which ensures that the data exchanged between different software components conforms to the defined structure and types.

On the other hand HTTP interceptors typically do small units of work, focusing on intercepting, inspecting, and modifying HTTP requests and responses. In Ballerina there are four kinds of HTTP interceptors, namely:
- Request Interceptors
- Request Error Interceptors
- Response Interceptors
- Response Error interceptors

As mentioned previously, an interceptor has the capability to manipulate the HTTP response and thereby would impact the possible response types for a given HTTP resource. Therefore, to accurately depict an HTTP service, the generated OpenAPI specification should consider the potential responses produced by the interceptor pipeline.

## Description

As mentioned above, the purpose of this proposal is to implement a feature to map interceptor responses into the generated OpenAPI specification. The key constraints of the proposed change is as follows,
- Only invoked for HTTP services inherited from `http:InterceptableService` type.
- Only invoked when the `createInterceptors` function of the HTTP service returns a type containing a tuple of HTTP interceptors.

Following is a sample Ballerina HTTP service with interceptors:
```ballerina
service http:InterceptableService /pets on new http:Listener(9090) {

   public function createInterceptors()
   	returns [
       	    ResInt2,
       	    ReqInt1,
       	    ReqErrorInt,
            ResErrInt,
       	    ReqInt2,
       	    ResInt1
   	] {
   	...;
   }

   ...
}
```
According to the above service declaration, following is the request/response interceptor pipeline flow looks like:

![Ballerina Interceptor Pipeline](https://github.com/ballerina-platform/ballerina-library/assets/96733889/ae8a5115-5cb1-4a51-9435-0bb6b01a6a3d)

To determine potential response types for resources within a given HTTP service, the following approach can be used:

#### 1. Capture meta-data for all the available HTTP interceptors in the ballerina project.

- Request Interceptor: relative resource path, interceptor type, return type
- Request Error interceptor: interceptor type, return type
- Response Interceptor: interceptor type, return type
- Response Error Interceptor: interceptor type, return type

#### 2. Identify the interceptor pipeline for the current HTTP service.

- Construct the request interceptor pipeline.
- Construct the response interceptor pipeline.

#### 3. Identify the effective response type for a given resource function.

**a.** Has to consider two paths when identifying the effective return type for a resource.

- Whether it is in the path of a request interceptor, if so identify the closest possible request error interceptor. Based on the response type of the request error interceptor, find the next possible response error interceptor.
- Check for the happy path where the resource is successfully executed (might return an error as well) and check the response flow for the possible response types.

**b.** Once all the possible response types are identified, concatenate all the response types with the resource response types and eliminate non-possible response types. 

## Testing

- **Unit Testing:** evaluate the individual components and core logic of the Ballerina OpenAPI tool, focusing on functions, methods, and modules to ensure correctness of the interceptor mapping.
- **Integration Testing:** assess the interactions and collaborations between various modules and components of the tool, verifying the seamless integration of interceptors into the OpenAPI specification.

**Comment by TharmiganK** [comment]
1. > - Only invoked for HTTP services inherited from `http:InterceptableService` type.
    > - Only invoked when the `createInterceptors` function of the HTTP service returns a type containing a tuple of HTTP interceptors.

    The first one is identifies whether the service is interceptable, so this proposal is only applicable to those services. 
    But second one is more of a constraint for the proposal, since thats the only fixed way to obtain the interceptors directly. If an interceptable service violates this constraint, we should provide an appropriate warning.
    
2. > Capture meta-data for all the available HTTP interceptors in the ballerina project.

     Does this mean we are going to collect the interceptor information regardless of whether they are used in the pipeline or not?
     
 3. > - Request Interceptor: effective service-path, interceptor type, return type
 
     Here we need the resource path rather the service path. Also we can only get the relative resource path from the interceptor alone. The base path depends on the HTTP service where we set the interceptor pipeline.
     
 4.  > Identify the interceptor pipeline for the current HTTP service.
 
      Here even though we can realise the pipeline into two - request interceptor pipeline and response interceptor pipeline. The decision should be made by considering them as a single pipeline rather than two different ones
      
 5. > - Whether it is in the path of a request interceptor, if so identify the closest possible request error interceptor. Based on the response type of the request error interceptor, find the next possible response error interceptor.
 
     I do not understand this. Can you explain a bit?  Are you referring to a scenario where an error is returned from a `RequestInterceptor`?
     
 6. > - Check for the happy path where the resource is successfully executed (might return an error as well) and check the response flow for the possible response types.
 
     Why are we referring this as a happy path when we also consider about error return type?
     
 7. > b. Once all the possible response types are identified, concatenate all the response types with the resource response types and eliminate non-possible response types.
 
     What do you mean by eliminating the non-possible response types?

**Comment by ayeshLK** [comment]
> The first one is identifies whether the service is interceptable, so this proposal is only applicable to those services.
But second one is more of a constraint for the proposal, since thats the only fixed way to obtain the interceptors directly. If an interceptable service violates this constraint, we should provide an appropriate warning.

+1 to provide a proper warning if the constraints are not met.

> Does this mean we are going to collect the interceptor information regardless of whether they are used in the pipeline or not?

For a given file, there can be multiple HTTP services defined. So, the next approach is to check all possible `http:InterceptableService` objects defined in a file and first find out the relevant interceptors and then visit the interceptors to gather meta-data. 

> Here we need the resource path rather the service path. Also we can only get the relative resource path from the interceptor alone. The base path depends on the HTTP service where we set the interceptor pipeline.

Agreed. This is just a mistake in the wording. @SachinAkash01 lets update the proposal appropriately.

> Here even though we can realise the pipeline into two - request interceptor pipeline and response interceptor pipeline. The decision should be made by considering them as a single pipeline rather than two different ones.

Can you please elaborate more on this with a sample ?

> I do not understand this. Can you explain a bit? Are you referring to a scenario where an error is returned from a `http:RequestInterceptor`?

Please correct me if I am wrong. An `http:RequestInterceptor` has one resource method which can return `http:NextService | error`. In that case, only possible response which could be returned from a request-interceptor pipeline would resides in the nearest HTTP request-error interceptor in case there is an error returned from the HTTP request interceptor. That is what we referred on this point.

> Why are we referring this as a happy path when we also consider about error return type?

In OAS generation happy path (we can say this is the simplest path) is there will be no interceptor pipeline and  we only have to consider the resource return types only (which includes error return types). The `happy-path` analogy is just to make this simplified into one word and it is based on my personal preference.

> What do you mean by eliminating the non-possible response types?

Lets say we have an HTTP response interceptor which return HTTP 200 OK for all the response (without checking for the resource return types). Then, we have to drop some return types from the generated OAS resource-responses right ?

**Comment by TharmiganK** [comment]
1. > Can you please elaborate more on this with a sample ?

     Lets say the `ReqInt1` returns a response(`anydata` or `http:Response` or `http:StatusCodeResponse`) then this response will hit the `ResInt2`. So what ever return types in the `ReqInt1` is not needed since they are going to be overwritten by the return types of `ResInt2`.

     Lets say there is no response interceptor above the `ReqInt1` then we need to consider the return types of `ReqInt1`.

     So even though, we think of it as a two pipelines, they act as one.

2. > Please correct me if I am wrong. An `http:RequestInterceptor` has one resource method which can return `http:NextService|error`. In that case, only possible response which could be returned from a request-interceptor pipeline would resides in the nearest HTTP request-error interceptor in case there is an error returned from the HTTP request interceptor. That is what we referred on this point.

     Actually, An `http:RequestInterceptor` can return `anydata|http:Response|http:StatusCodeResponse|http:NextService|error` i.e. it can return a response or it can pass the request to the next interceptor/service in the pipeline

3. > In OAS generation happy path (we can say this is the simplest path) is when there will be no interceptor pipeline and we only have to consider the resource return types only (which includes error return types).

     Got it. IMO If there is no interceptor pipeline then this proposal should not have an impact on the return type mapper. So, I think it would be better if we have a separate component like `ResponseMapperWithInterceptors` which extends the `ResponseMapper` interface(which is added with the restructuring). So when we found an interceptable service, we provide this new implementation rather than the default response mapper implementation.

4. > Lets say we have an HTTP response interceptor which return HTTP 200 OK for all the response (without checking for the resource return types). Then, we have to drop some return types from the generated OAS resource-responses right ?

     In the step 3, we are finding the effective return type right? So if there is a response interceptor which overwrite all the responses to HTTP 200 OK, there is no need to obtain the return types of other service. The effective return type can be directly found by the response interceptor alone.

**Comment by SachinAkash01** [comment]
@ayeshLK @lnash94 @TharmiganK and myself had a discussion regarding the above concerns and came up with following decisions,

- Instead of writing a visitor to get the required information like return type(s) of the `createInterceptors()` function, we can directly use semantic model to get those data since it act as a types API.
- Write a separate util `InterceptableResponseMapperImpl` which extends the `ResponseMapper`  for the implementation of the interceptor mapping.

**Comment by SachinAkash01** [comment]
### When incorporating this functionality, we will adhere to the following design choices:
- We will have two response mappers, one acts as a default one (`ResponseMapperImpl) that extends the `ResponseMapper` which has already been implemented with the restructuring of the Ballerina to OAS module.
- The second response mapper named `InterceptableResponseMapperImpl` that extends the `ResponseMapper` interface to encapsulate the logic for mapping responses related to the `http:InterceptableService`.
  - Employ the semantic model to inspect the `ServiceDeclarationNode` and member functions to ascertain whether the provided HTTP service qualifies as an `http:InterceptableService`. Subsequently, build the interceptor pipeline.
  - Utilize the generated interceptor pipeline to implement the logic for constructing potential API responses specific to an HTTP resource within the given service.
- If the interceptable service (`http:InterceptableService`) does not adhere to the predefined constraints, then it should fallback to the default response mapper.
- Implement a factory which supplies the response mapper implementation based on the predefined constraints.
- When the `InterceptableResponseMapper` is involved, build the interceptor pipeline using the interceptor pipeline definition and semantic model.
- The pipeline has the following information about the interceptable service,
  - Interceptor type
  - Relative resource path (applicable only for the request interceptors)
  - Return types
- Effective return types for an interceptable service is found by evaluating the interceptor pipeline.

**Comment by TharmiganK** [comment]
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/5156

**Comment by TharmiganK** [comment]
The implementation in https://github.com/ballerina-platform/openapi-tools/pull/1599 is incomplete and there are few gaps we need to address:
1. Resource interceptor matching based on the resource method and path. We should implement a similar approach in dispatcher to compare interceptor path with target resource path. The interceptor is only invokable if the path match.
2. The logic to find the effective return type should be revisited since it is failing for some common scenarios when there are multiple interceptors.

**Comment by TharmiganK** [comment]
**Resource path matcher implementation**

Two linked lists should be implemented to compare a target resource path with a reference resource path(in the interceptor).

There are four types of path segment nodes in the list:
1. Dot path segment node
2. Named path segment node
3. Path parameter path segment node
4. Path rest parameter path segment node

The matcher logic should be based on the target and reference path segment node types

The logic can be described by the following diagram:
![Resource path matcher](https://github.com/ballerina-platform/ballerina-library/assets/63336800/6b910577-bbca-459b-b376-59ca61b088cb)

**Comment by TharmiganK** [comment]
**Effective response finder with interceptors**

A double linked list is implemented to represent the interceptor pipeline.

There are five type of nodes in the list:
- Request interceptor
- Request error interceptor
- Response interceptor
- Response error interceptor
- Target resource

Each node expose the next interceptor to invoke via the following methods:
- `nextInReqPath` - returns the next request interceptor in the request path
- `nextInResPath` - returns the next response interceptor in the response path
- `nextInReqErrPath` - returns the next request error interceptor in the request path
- `nextInResErrPath` - returns the next response error interceptor in the response path

The sample pipeline can be visualised as follows:
![Interceptor Pipeline Sample](https://github.com/ballerina-platform/ballerina-library/assets/63336800/35ea3d89-c305-4e11-bd8d-051ecf829c65)

Each interceptor node has its own logic to call/pass the return types, we can define it by checking the following scenarios:
1. When the node is a request or request error interceptor:
![Request Interceptor Mapping Logic](https://github.com/ballerina-platform/ballerina-library/assets/63336800/94f68665-900c-4ec1-9f34-87ef8827deaa)
2. When the node is a response or response error interceptor:
![Response Interceptor Mapping Logic](https://github.com/ballerina-platform/ballerina-library/assets/63336800/ef367607-991e-407b-913f-0e095864e625)
3. When the node is the target resource:
![Target Resource Mapping Logic](https://github.com/ballerina-platform/ballerina-library/assets/63336800/1c1841c9-81be-4dce-b898-03446cb34325)
