### ISSUE TITLE
[Ballerina-GRPC] Unable to configure header size in Ballerina gRPC server configuration

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-platform/ballerina-library#5969]
**Description:**
I'm getting the following errors when trying to invoke a gRPC service from a Ballerina gRPC client, using a JWT header. The JWT is a bit lengthy.

##### Error 01
```
Compiling source
        viduranga/bal_grpc_client:0.1.0

Running executable

error: HTTP status code 431
invalid content-type: null
MESSAGE DATA:
```

##### Error 02
```
Compiling source
        viduranga/bal_grpc_client:0.1.0

Running executable

error: Remote host closed the connection before initiating inbound response
```

These error do not get thrown when the length of the JWT is shortened. Hence I believe this has something to do with the allowed header size.

Although a maximum header size configuration is available in the [HTTP library](https://central.ballerina.io/ballerina/http/2.10.5#RequestLimitConfigs), I was not able to find such a configuration in the gRPC library

**Steps to reproduce:**

- Create a Ballerina gRPC server and a client
- Send a request to the server from the client attaching a considerably large header value.

**Affected Versions:**
```
Ballerina 2201.8.0 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.0
```

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dilanSachi** [comment]
@vlgunarathne We have released gRPC v1.10.6 with the fix. You can use the field `maxHeaderLength` in `grpc:ListenerConfiguration` to increase the header size.
