### ISSUE TITLE
[Bal to OAS] Ballerina HATEOAS to OAS mapping does not work when used with `bal build` command or OpenAPI built-in extension

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#5981]
**Description:**
> $subject

**Comment by SachinAkash01** [comment]
Fixed this issue with following commits:
- [90eb48d672af742702eb9b00245208ce99b7c871](https://github.com/ballerina-platform/openapi-tools/pull/1589/commits/90eb48d672af742702eb9b00245208ce99b7c871)
- [4c8bdc3e56d26fd80f0fd8fce7c334516cfaa6c7](https://github.com/ballerina-platform/openapi-tools/pull/1589/commits/4c8bdc3e56d26fd80f0fd8fce7c334516cfaa6c7)
