### ISSUE TITLE
Add the capability to generate the persist data model by introspecting an existing database schema

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-library#5982]
In application development, the need to work with existing databases is prevalent. Currently, `bal persist` is designed to work with new databases since it supports only generating the database schema from the persist data model.  There is no way to generate the persist data model from an existing database schema. 

This feature is critical to support enterprise integration scenarios that require connecting to existing databases.

**Comment by sameerajayasoma** [comment]
The following proposal by @daneshk is critical to design the introspection feature. 
https://github.com/ballerina-platform/ballerina-library/issues/5942

It attempts to develop a model that allows developers to customize the generation of database schemas from a bal persist data model.

**Comment by daneshk** [comment]
This is already done and shipped with update 09. Hence closing the issue.
