### ISSUE TITLE
PR build common template for windows failing

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#5999]
**Description:**
$subject

The step for stepping env variables seems to be failing,

https://github.com/ballerina-platform/module-ballerinax-java.jdbc/actions/runs/7708024111/job/21006284196?pr=1103

**Comment by niveathika** [comment]
PR Merge template also fails with Graphql issue,

https://github.com/ballerina-platform/module-ballerinax-postgresql/actions/runs/7719016341

**Comment by Nuvindu** [comment]
I have re-run the workflows now and builds were successful for both.
https://github.com/ballerina-platform/module-ballerinax-java.jdbc/actions/runs/7708024111/job/21056197070?pr=1103

https://github.com/ballerina-platform/module-ballerinax-postgresql/actions/runs/7719016341/job/21056736884
