### ISSUE TITLE
Error Retrieving Partial Objects with byte range in ballerinax/aws.s3 Library

### ISSUE THREAD

**Issue by nisuraaa** [ballerina-platform/ballerina-library#6007]
**Description:**
Attempting to download objects partially, by using byte range in the objectRetrievalHeaders and passing it as an argument to the getObject function results in an error. The error occurs when the server responds with a status code of 206 - Partial Content, indicating a successful partial retrieval. However, the getObject function only considers a status code of 200 as successful, leading to the following error:

![image](https://github.com/ballerina-platform/ballerina-library/assets/64645496/8360bd28-f66a-4b3c-bb1c-7aa4411a1476)

```
error GenericClientError ("Error occurred while retrieving the xml payload from the response",error ParserError ("Error occurred while extracting xml data from entity: error("failed to parse xml: Unexpected character 'T' (code 84) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]")"))
```

Debugging the library code reveals that the getObject function considers only a 200 status code as a success.

**Steps to reproduce:**

1. Create an S3 bucket with sample objects or use an existing one.
2. Set up the objectRetrievalHeaders with byte range specifications for partial object retrieval.
3. Call the getObject function with the specified byte range headers.

**Affected Versions:**
Ballerina version: 2201.4.1
ballerinax/aws.s3 version: 3.2.0 

**OS, DB, other environment details and versions:**
OS: Ubuntu 22.04.3 LTS
openjdk 11.0.2 2019-01-15

**Comment by ShammiL** [comment]
In the [`getObject` implementation](https://github.com/ballerina-platform/module-ballerinax-aws.s3/blob/master/ballerina/client.bal#L168) all other 2xx codes except 200 is considered unsuccessful an returns the payload as an error.
