### ISSUE TITLE
The generated graphql schema contains a comment line which is not marked as a comment

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-library#6021]
**Description:**

I am using the code in https://ballerina.io/learn/write-a-graphql-api-with-ballerina/#the-complete-code

Generate the schema using the tool with following command.

```
bal graphql -i service.bal 
```

The output is as follows.

```
type Query {
  all: [CovidData!]!
  filter(isoCode: String!): CovidData
}

type CovidData {
  isoCode: String!
  country: String!
  cases: Decimal
  deaths: Decimal
  recovered: Decimal
  active: Decimal
}

"The `Decimal` type corresponds to a subset of IEEE 754-2008 128-bit decimal (radix 10) floating point numbers"
scalar Decimal

type Mutation {
  add(entry: CovidEntry!): CovidData!
}

input CovidEntry {
  isoCode: String!
  country: String!
  cases: Decimal
  deaths: Decimal
  recovered: Decimal
  active: Decimal
}
```

The comment line on decimal is not added with `#`

<img width="918" alt="image" src="https://github.com/ballerina-platform/ballerina-library/assets/16300038/357ccb0b-be1e-47ef-925d-b529fe3e85e8">

**Comment by DimuthuMadushan** [comment]
@anupama-pathirage This is the standard way of defining the [description](https://spec.graphql.org/draft/#sec-Descriptions) of types in GraphQL Schema Definition Language(SDL).
