### ISSUE TITLE
Open AI `/edits` endpoint have been removed  

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-library#6024]
**Description:**
The Open AI has [deprecated](https://platform.openai.com/docs/deprecations/edit-models-endpoint) several API endpoints and on the first week of January 2024 they have shutdown those APIs. Ballerina `openai.text` library Client provides an API called `/edits` which has been affected by this. Currently the requests send this API gives an error. 

We have to remove this API endpoint from the client and need to implement a new API endpoint using this [chat completions](https://platform.openai.com/docs/api-reference/chat/create) API.

Because of this several samples in the [ai usecase](https://ballerina.io/usecases/ai/) page won't work.

**Steps to reproduce:**
Run the sample in [ai-usecases](https://github.com/ballerina-guides/ai-samples/blob/main/correct_grammar_and_spelling_in_text_using_openai/main.bal).

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@NipunaMadhushan can we close this as this is merged (assuming connector is fixed now? )https://github.com/ballerina-guides/ai-samples/pull/71

**Comment by NipunaRanasinghe** [comment]
@anupama-pathirage Yes I think we are good to close this as we recently updated all the AI samples with the latest changes. @DevAakif please check and confirm.

**Comment by DevAakif** [comment]
> @anupama-pathirage Yes I think we are good to close this as we recently updated all the AI samples with the latest changes.
> 
> @DevAakif please confirm.

@NipunaRanasinghe Yes. I have updated and tested all the AI samples
