### ISSUE TITLE
Add support for new advanced database annotations when generating database client in `bal persist`

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-library#6035]
**Description:**
This task is to add support for annotations when generating the database client API in the `bal persist` module. The new annotations were added with respect to the issue #6013.

**Describe your task(s)**
- Read the annotations in `bal persist generate`
- Handle the mapping annotation
- Handle the generated annotation
- Handle the type mapping annotation
- Handle the relation annotation
- Handle the index and unique index annotations

**Comment by daneshk** [comment]
This task is a part of the parent issue: https://github.com/ballerina-platform/ballerina-library/issues/5982
This task is already done. Hence closing the issue. This fix will be sent with the other fixes.
