### ISSUE TITLE
Google Sheet append add single quote when inserting numbers.

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-library#6039]
**Description:**
We have a use case where we append rows to a Google sheet. 
https://github.com/ballerina-platform/ballerina-release/blob/master/central_stats/main.bal#L158

The numbers in the sheet get a single quote as a prefix.

ballerinax | '1294 |' 2/8/2024
-- | -- | --

Is there a way to remove this single quote from the data?

**Steps to reproduce:**

**Affected Versions:**
3.5.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
I can't reproduce this issue, This API works fine for me, I had to explicitly send the data with a single quote ex: "'sample", to get the same result. Don't think we have to strip that if the user is explicitly adding it. @anuruddhal Are you sure the data sent in the code sample you have shared are not sending this single quote with it? Can we get a sample value of the actual data sent?

**Comment by anuruddhal** [comment]
@aashikam 

Following are the sample data that get inserted.

```
[["United States","package-pull","10600","2/12/2024"],["Sri Lanka","package-pull","275","2/12/2024"],["Pakistan","package-pull","1","2/12/2024"],["Australia","package-pull","10","2/12/2024"],["Iran","package-pull","3","2/12/2024"],["Singapore","package-pull","2","2/12/2024"],["Germany","package-pull","1","2/12/2024"]]
```

**Comment by aashikam** [comment]
This is an expected behavior in the Sheets REST API. https://github.com/burnash/gspread/issues/524 

Please try setting the valueInputOption to "USER_ENTERED".
Example:
```
 _ = check spreadsheetClient->appendValues(spreadsheetId, values, a1Range, "USER_ENTERED");
```

**Comment by anuruddhal** [comment]
@aashikam 
Setting the valueInputOption to "USER_ENTERED" worked. Thanks for looking into this.
