### ISSUE TITLE
 Support for CSRF token header from the SAP client itself.

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#6047]
**Description:**
SAP for prevents of Man in the middle attacks has implemented CSRF token validation in its endpoint

We need this token to be fetched and updated in the request form the client itself. to improve usability.

**Comment by TharmiganK** [comment]
This might be a possible use case for [client interceptors](https://github.com/ballerina-platform/ballerina-library/issues/4329)

Client interceptors are not yet implemented in the `http` module. For now you have to use a wrapper client. 

I have pushed a Ballerina wrapper client to central: https://central.ballerina.io/tharmigank/http.client.wrapper/0.0.2
Sample usage:
```ballerina
wrapper:InterceptFunction interceptFunc = isolated function(string path, string method, http:RequestMessage message,
        string? mediaType, map<string|string[]>? headers, wrapper:WrapperCtxMap ctxMap) returns wrapper:ModifiedRequest {

    map<string|string[]> modifiedHeaders = {"X-Test": "test"};
    foreach string key in ctxMap.keys() {
        // getWithType is also available on ctxMap
        io:println("Key: " + key + ", Value: " + ctxMap.get(key).toString());
    }
    if headers is map<string|string[]> {
        foreach [string, string|string[]] entry in headers.entries() {
            modifiedHeaders[entry[0]] = entry[1];
        }
    }
    return {
        message,
        headers: modifiedHeaders,
        mediaType
    };
};

map<anydata> ctxMap = {
    "key1": 3,
    "key2": "value2"
};
wrapper:Client clientEp = check new ("http://localhost:9090", interceptFunc = interceptFunc, ctxMap = ctxMap);
```
Source repository: https://github.com/TharmiganK/module-tharmigank-http-client-wrapper

**Comment by niveathika** [comment]
The connector is fully completed and pushed to https://github.com/niveathika/module-ballerinax-sap

This needs to be migrated to ballerina repository.

**Comment by niveathika** [comment]
The client is migrated to https://github.com/ballerina-platform/module-ballerinax-sap, thus closing the issue
