### ISSUE TITLE
Support Server Sent Events for OpenAPI connectors

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-library#6049]
**Description:**
$Subject.

In Azure openai connector, when stream is set to true, it responds with Server sent events with the content type text/event-stream. As of now, it fails but we need to see if we can handle this scenario.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment]
Seems like ballerina http also doesn't have the support for this feature. 
https://github.com/ballerina-platform/ballerina-library/issues/3188

**Comment by lnash94** [comment]
Close this issue with this PR https://github.com/ballerina-platform/openapi-tools/pull/1742
