### ISSUE TITLE
Support Options for `formXmlStringWithType` and `fromXmlWithType`

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-library#6073]
**Description:**
Allow users to override the default behaviour of XML data library using options such as 

- attributePrefix
- textFieldName
- isProjectionAllowed

```
type Options record {|
    string attributePrefix = "";
    string textFieldName = "#content";
    boolean isProjectionAllowed = true;
|};
``` 

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Alternative name:  `allowFlexibleDataProjection` `allowDataProjection`

**Comment by prakanth97** [comment]
> Alternative name: `allowFlexibleDataProjection` `allowDataProjection`

+1 for `allowDataProjection`

**Comment by prakanth97** [comment]
Options can be passed when converting from XML source to record and record to xml. 

Hence introduce two options type as follow

```
# Represent the options that can be used to modify the behaviour of conversion.
#
# + attributePrefix - prefix added for attribute fields in the record 
# + textFieldName - field name for the text field
public type Options record {|
    string attributePrefix = EMPTY_STRING;
    string textFieldName = "#content";
|};

# Represent the options that can be used to modify the behaviour of conversion in `fromXmlStringWithType` and `fromXmlWithType`.
#
# + allowDataProjection - enable or disable projection
public type SourceOptions record {|
    *Options;
    boolean allowDataProjection = true;
|};
```

The SourceOptions is used when converting from xml source to record using `fromXmlWithType` and `fromXmlStringWithType` function.

The Options is used when converting records to the xml value using `toXml` function.

Refer: https://github.com/ballerina-platform/module-ballerina-data-xmldata/pull/6
