### ISSUE TITLE
Draft a connector design for MS Dynamics365 Business Central connector.

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-library#6116]
### Related Epic Issue
Issue [https://github.com/ballerina-platform/ballerina-library/issues/6115](https://github.com/ballerina-platform/ballerina-library/issues/6115)

### Task Description
- Draft a connector design for MS Dynamics365 Business Central connector.

**Comment by RDPerera** [comment]
Design documentation: https://docs.google.com/document/d/1D4kbRnTrNFUvySCqdPvYAf66ZaQgXVdGlPXuhVK54Mc/edit?usp=sharing

**Comment by niveathika** [comment]
Closing as design is accepted after review
