### ISSUE TITLE
Community-driven test suites are dropped from both TOML and YAML repositories

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-library#6129]
**Description:**
Both TOML and YAML repositories rely on Git submodules as the resources for testing the read APIs of the modules. However, these submodules are dropped from the current versions of both modules. Please refer to the following `.gitmodules` file for each respective modules, and these should be integrated to the current versions.

- [x] [ballerina/toml ](https://github.com/ballerina-platform/module-ballerina-toml/blob/8eed871c7bf0de5a1951da072988385698ea06b7/.gitmodules)
- [x] [ballerina/yaml](https://github.com/nipunayf/ballerina-yaml/blob/main/.gitmodules) 

**Affected Versions:**
ballerina/yaml 0.5.1
ballerina/toml 0.5.0

**OS, DB, other environment details and versions:**
Ballerina 2201.8.5 (Swan Lake Update 8)
OS: macOS 14.2.1 23C71
JDK: openjdk 17.0.8 2023-07-18

**Comment by RDPerera** [comment]
Closing as it's implemented by following PRs,
- https://github.com/ballerina-platform/module-ballerina-toml/pull/38
- https://github.com/ballerina-platform/module-ballerina-yaml/pull/42
