### ISSUE TITLE
Add a standard string conversion for Civil type

### ISSUE THREAD

**Issue by dinukaamarasinghe817** [ballerina-platform/ballerina-library#6137]
**Description:**
Need to provide standards methods to convert a `time:Civil` value to a `string` value and a `string` value to a `time:Civil` value with `utcOffset` and `timeAbbrev`

**Steps to reproduce:**
1. Create a `time:Civil` value with a `utcfOffset` and a `timeAbbrev`
2. Convert the `time:Civil` value to a `string` using `time:civilToString` method
3. Conver the converted `string` value back to a `time:Civil` value using `time:civilFromString` method
4. Final value is not equivalent to the previous original value.

**Affected modules**
- Bal Persist for Redis DB : https://github.com/ballerina-platform/module-ballerinax-persist.redis

**Comment by TharmiganK** [comment]
Tried the following sample with the latest Ballerina version(2201.10.0) and it is working as expected:
```bal
public function main() returns error? {
    time:Civil civil1 = {
        year: 2022,
        month: 1,
        day: 29,
        hour: 22,
        minute: 48,
        second: 0,
        timeAbbrev: "Asia/Colombo",
        utcOffset: {hours: 5, minutes: 30}
    };
    string civilString = check time:civilToString(civil1);
    io:println("Civil Time string: ", civil1);
    time:Civil civil2 = check time:civilFromString(civilString);
    io:println("Civil Time 1: ", civil1);
    io:println("Civil Time 2: ", civil2);
}
```

```console
$ bal run
Compiling source
        tharmigan/zone_bbe:0.1.0

Running executable

Civil Time string: {"utcOffset":{"hours":5,"minutes":30},"timeAbbrev":"Asia/Colombo","year":2022,"month":1,"day":29,"hour":22,"minute":48,"second":0}
Civil Time 1: {"utcOffset":{"hours":5,"minutes":30},"timeAbbrev":"Asia/Colombo","year":2022,"month":1,"day":29,"hour":22,"minute":48,"second":0}
Civil Time 2: {"utcOffset":{"hours":5,"minutes":30},"timeAbbrev":"+05:30","dayOfWeek":6,"year":2022,"month":1,"day":29,"hour":22,"minute":48}
```

This is fixed with https://github.com/ballerina-platform/ballerina-library/issues/6986
