### ISSUE TITLE
Make changes to advanced SQL annotation definitions

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-library#6180]
**Description:**
According to the new design revisions done in task #5942, it is required to implement the revised changes to the [`module-ballerina-persist`](https://github.com/ballerina-platform/module-ballerina-persist), [`module-ballerinax-persist.sql` ](https://github.com/ballerina-platform/module-ballerinax-persist.sql) and [`persist-tools`](https://github.com/ballerina-platform/persist-tools).

**Describe your task(s)**
- Change the `@sql:Mapping` annotation as follows.
```Ballerina
public type NameConfig record {|
    string value;
|};

public annotation NameConfig Name on type, record field;
```
- Change the `@sql:Index` and `@sql:UniqueIndex` annotation definition as follows.
```Ballerina
public type IndexConfig record {|
    string|string[]? name = ();
|};
```
- Rename `@sql:VarChar` annotation to `@sql:Varchar`.

**Comment by daneshk** [comment]
And the `@sql:Relation` annotation, change the `refs` field to `keys`
