### ISSUE TITLE
Add advanced compiler validations for custom foreign keys

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-library#6188]
**Description:**
Currently, when you define a custom foreign key as follows,
```Ballerina
public type Person record {|
    @sql:Char {length:10}
    readonly string name;
    int age;
    Car[] cars;
|};

public type Car record {|
    readonly string make;
    int ownerName;
    @sql:Relation {keys: ["ownerName"]}
    Person owner;
|};
```
The compiler diagnostics reports an error as the foreign key type and the primary key type of the referring entity mismatches. However, if the user defines a foreign key with mismatching annotations as follows,
```Ballerina
public type Person record {|
  @sql:Char {length:10}
  readonly string name;
  int age;
  Car[] cars;
|};

public type Car record {|
    readonly string make;
    @sql:Varchar {length:20}
    string ownerName;
    @sql:Relation {keys: ["ownerName"]}
    Person owner;
|};
```
There would be no compilation errors and it would just override the annotation and define the foreign key matching the primary key type as follows, since the actual data types are matching.
```SQL
CREATE TABLE `Person` (
	`name` CHAR(10) NOT NULL,
	`age` INT NOT NULL,
	PRIMARY KEY(`name`)
);

CREATE TABLE `Car` (
	`make` VARCHAR(191) NOT NULL,
	`ownerName` CHAR(10) NOT NULL,
	FOREIGN KEY(`ownerName`) REFERENCES `Person`(`name`),
	PRIMARY KEY(`make`)
);
```
This task is to ensure that the developer intent is clear, and throw an error when ever the annotations do not match.

**Describe your task(s)**
- Extend compiler validation by checking for annotation on the foreign key as well.

**Comment by Bhashinee** [comment]
Closing the issue as this is comepleted with https://github.com/ballerina-platform/module-ballerinax-persist.sql/pull/61
