### ISSUE TITLE
Improve migration support for advanced SQL annotations

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-library#6189]
**Description:**
While migrations do work with some of the new annotations, it does not work in some scenarios as follows.
- Add an `@sql:Generated` annotation to an existing primary key
- Add an `@sql:Char`, `@sql:Varchar` or `@sql:Decimal` annotation to an existing field
- Add `@sql:Index` or `@sql:UniqueIndex` annotation to an existing field
- Add an `@sql:Name` annotation to an existing field or entity
- Create a new entity with `@sql:Name` annotation on the entity name or field name
- No support for `@sql:Relation` annotation

**Describe your task(s)**
- Implement support for the new SQL annotations

**Comment by hasathcharu** [comment]
The PR [/ballerina-platform/persist-tools/pull/343](https://github.com/ballerina-platform/persist-tools/pull/343) is added improve the functionality of `bal persist migrate` to support more scenarios such as composite primary keys and some other edge cases. 

Moreover, the test suite is refactored for the intent to be more clear and test assertion is updated to assert all the generated migration scripts with the expected output which was previously ignored. 

This PR also contains some refactoring to make room to support advanced SQL annotations which will be done next.

More information about this can be found by referring to the progress document [[1](https://docs.google.com/document/d/1gSndfB8lUoMQWmVCf5WIhLxBQPmkEAym7e9l3nzGtPc/edit?usp=sharing)].

[1] https://docs.google.com/document/d/1gSndfB8lUoMQWmVCf5WIhLxBQPmkEAym7e9l3nzGtPc/edit?usp=sharing

**Comment by daneshk** [comment]
This fix is already merged into the master branch. Hence closing the issue.

**Comment by hasathcharu** [comment]
The PR [/ballerina-platform/persist-tools/pull/344](https://github.com/ballerina-platform/persist-tools/pull/344) adds support for all the annotations except `@sql:Index` and `@sql:UniqueIndex` annotations. The next PR will add support for the aforementioned annotations as well.
For more information about supported scenarios, please refer the progress document [[1](https://docs.google.com/document/d/1gSndfB8lUoMQWmVCf5WIhLxBQPmkEAym7e9l3nzGtPc/edit?usp=sharing)].

[1] https://docs.google.com/document/d/1gSndfB8lUoMQWmVCf5WIhLxBQPmkEAym7e9l3nzGtPc/edit?usp=sharing

**Comment by hasathcharu** [comment]
As discussed offline, it was decided to bring support for `@sql:Index` and `@sql:UniqueIndex` annotations for `bal persist migrate` in a future update.

**Comment by hasathcharu** [comment]
Support for `@sql:Index` and `@sql:UniqueIndex` annotations are added with PR [/ballerina-platform/persist-tools/pull/348](https://github.com/ballerina-platform/persist-tools/pull/348), completing this task.
