### ISSUE TITLE
Fix OpenAPI Spec Generation Test Failures with lang time stampe `2201.9.0-20240319-112900-1e0b4bcf`

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#6197]
**Description:**
$Subject
lang timestamp : [2201.9.0-20240319-112900-1e0b4bcf](https://github.com/ballerina-platform/ballerina-lang/packages/412934?version=2201.9.0-20240319-112900-1e0b4bcf)

**Comment by TharmiganK** [comment]
Closing in favour of same issue tracked via: https://github.com/ballerina-platform/ballerina-library/issues/6217
