### ISSUE TITLE
Release Ballerina ASB connector

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-library#6211]
**Description:**
Release Ballerina ASB connector

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayeshLK** [comment]
With following task [1] we have released the revamped ASB connector. Hence, closing this issue.

[1] - https://github.com/ballerina-platform/ballerina-library/issues/6565
