### ISSUE TITLE
Bal persist migrate command failed to generate SQL commands if I remove the optionality of a model field

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-library#6232]
I updated an optional field to a mandatory field in the `model.bal`, then ran the `bal persist migrate` command. The corresponding sql migration commands are missing in the generated migration script.

**Comment by sameerajayasoma** [comment]
See: https://github.com/sameerajayasoma/expense-tracker/blob/main/budget-app-backend/persist/migrations/20240325220612_dateTime_change_2/script.sql

**Comment by daneshk** [comment]
This is fixed with migrate command refactor work by @hasathcharu.
