### ISSUE TITLE
WebSub module build is hanging with the SL Update 9 lang changes

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#6266]
**Description:**
> $subject

PR build failure:
- https://github.com/ballerina-platform/ballerina-lang/actions/runs/8479400930/job/23233417207?pr=42129

**Comment by ayeshLK** [comment]
This issue occurs due to WebSub unsubscription test case [1] In this test case we are invoking the `gracefulStop` on `websub:Listener` manually to test the unsubscription flow. But, once the test case completed successfully it seems like the runtime is invoking the `gracefulStop` again. @gabilang can you comment on this behavior. 

[1] - [https://github.com/ballerina-platform/module-ballerina-websub/blob/a99530c7dbc5b2226c3a99fbcc4790a8daf98bff/ballerina/tests/unsubscription_test.bal#L89](https://github.com/ballerina-platform/module-ballerina-websub/blob/a99530c7dbc5b2226c3a99fbcc4790a8daf98bff/ballerina/tests/unsubscription_test.bal#L89)

**Comment by gabilang** [comment]
It seems we do not need to call the `gracefulStop()` stop manually for the registered listeners. It'll get called during the shutdown sequence. 
Btw it seems that we need to investigate the hanging behavior when the gracefulStop() method being called twice (in common it will not happen).
