### ISSUE TITLE
Add introspection support for PostgreSQL data store

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-library#6333]
**Description:**
This task is to add database introspection support for the PostgreSQL databases in the `bal persist` CLI tool.

**Describe your task(s)**
- Study queries required to retrieve the database schema
- Implement logic to map PostgreSQL specific data types to Ballerina types
- Add tests to cover the PostgreSQL data store

**Comment by daneshk** [comment]
The fix is already merged into the main branch. Hence closing the issue
