### ISSUE TITLE
Create a blog post and a video for Redis DB in bal persist

### ISSUE THREAD

**Issue by dinukaamarasinghe817** [ballerina-platform/ballerina-library#6350]
**Description:**
To market the Redis DB support in `bal persist` we need to show how a real-world use case can be implemented via `bal persist` easily.

**Describe your task(s)**

1. Find a proper use case that can be implemented using new features in Redis
2. Design the flow of the use case.
3. Implement the use case using `bal persist`
4. Create a blog post and a video tutorial

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
This is captured in 
https://github.com/wso2-enterprise/marketing-ballerina/issues/240
https://github.com/wso2-enterprise/marketing-ballerina/issues/240
