### ISSUE TITLE
`bal persist migrate` recreates a name annotated entity each time

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-library#6374]
**Description:**

If there is a `model.bal` with an entity with `@sql:Name` annotation, the `CREATE TABLE` script for the table gets regenerated in the migration script even if the latest `model.bal` file contains the said entity.

**Steps to reproduce:**

Initial `model.bal` file.

```Ballerina
@sql:Name {value: "appointment"}
public type Appointment record {|
    readonly int id;
    string reason;
    time:Civil appointmentTime;
|};
```

Run the `migrate` command once.

Run the `migrate` command another time.

Output `script.sql` in the second time.

```SQL
CREATE TABLE `appointment`(
    `id` INT NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `appointmentTime` DATETIME NOT NULL,
   PRIMARY KEY(`id`)
);
```

**Comment by daneshk** [comment]
The fix is already merged. Hense closing the issue.
