### ISSUE TITLE
Add GraphQL ID Type Support in Service Generation

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-library#6381]
**Description:**

The Ballerina GraphQL tool supports generating Ballerina code from a GraphQL schema. Currently, this generated code does not support adding `ID` type support. 

There is an issue when generating the Ballerina type of an `ID` type field. But as a starting point, we can use the Ballerina `string` type as the type and use the `@graphql:ID` annotation to generate the type.

**Comment by m-tabish** [comment]
Kindly assign this to me, under Hacktoberfest 2024. I will try to solve this

**Comment by DimuthuMadushan** [comment]
👋 Welcome, @m-tabish  🚀
 We have assigned this issue for you.

**Comment by Ishad-M-I-M** [comment]
Hi @DimuthuMadushan , Can I get this issue assigned to me if there's no progress yet from @m-tabish ?

**Comment by m-tabish** [comment]
Sure @Ishad-M-I-M can take this up , i wasn't able to solve this.

**Comment by ThisaruGuruge** [comment]
Thank you for looking into this @m-tabish. 

@Ishad-M-I-M Glad you are interested in this. I have assigned this to you. Happy coding!
