### ISSUE TITLE
Codegen didn't return error if the schema file is not found

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-library#6385]
**Description:**
$subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ballerina 2201.8.2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
When following the https://ballerina.io/learn/edi-tool/#code-generation-example and executing the following command by passing the wrong path for the schema file path, it runs without any error. But didn't generate the source. 
```
bal edi codegen -s resources/edi-schema.json -o modules/hmartOrder/orderRecords.bal
```

**Related Issues:**

**Comment by niveathika** [comment]
This is fixed in latest version 
```log
Error reading schema json file: no such file or directory: ~/edi_to_record/resources/edi-schema.json
```
