### ISSUE TITLE
[JMS] Improve JMS Endpoint Initialization 

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-library#6408]
<a href="https://github.com/aashikam"><img src="https://avatars3.githubusercontent.com/u/39673615?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aashikam](https://github.com/aashikam)**
_Friday Nov 16, 2018 at 12:13 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-lang/issues/11444_

----

**Description:**

The `username` and `password` fields are redundant in the ConnectionConfiguration record as they can be specified in the `providerUrl` as well (`    string providerUrl = "amqp://admin:admin@ballerina/default?brokerlist='tcp://localhost:5672'";`). Need to construct the provider url internally by taking the `username` and `password` separately. 

```ballerina
public type ConnectionConfiguration record {
    string initialContextFactory = "wso2mbInitialContextFactory";
    string providerUrl = "amqp://admin:admin@ballerina/default?brokerlist='tcp://localhost:5672'";
    string connectionFactoryName = "ConnectionFactory";
    string? username = ();
    string? password = ();
    map properties = {};
    !...
};
```

**Suggested Labels (optional):**
Component/jms, Type/Improvement 

**Suggested Assignees (optional):**
Arshika

**Comment by ayeshLK** [comment]
With the new design username and password fields are optional [1] and the developer has the flexibility to provide them in the `providerURL` itself.

[1] - https://central.ballerina.io/ballerinax/java.jms/1.0.1#ConnectionConfiguration

**Comment by ayeshLK** [comment]
> [<img alt="" width="48" height="48" src="https://avatars2.githubusercontent.com/u/8640149?v=4">](https://github.com/orthoxerox) **Comment by [orthoxerox](https://github.com/orthoxerox)** _Friday Dec 07, 2018 at 14:27 GMT_
> 
> Not all message brokers have initial context factories that accept provider URLs that point to a broker instance. IBM MQ, for example, is often used with `com.sun.jndi.fscontext.RefFSContextFactory` or `com.sun.jndi.ldap.LdapCtxFactory`, which point to a .bindings file location or a LDAP resource respectively.
> 
> In my opinion, it's better to avoid initial context factories altogether if you're not running your program on a JavaEE app server. I've written my own trivial initial context factory to connect Ballerina to IBM MQ, but it's a dirty hack.

With the latest design, the developer can point to a `.bindings` file location as the provider URL with the mentioned initial-context-factory instances. For more information you can refer to this article [1] 

[1] - https://ayesh9303.medium.com/jms-with-ballerina-lang-part-6-35ac842014a9

**Comment by ayeshLK** [comment]
Since, all the cases have been addressed by the latest Ballerina `java.jms` design will close this issue. If you have any further questions and clarifications please feel free to re-open this issue. The latest Ballerina `java.jms` implementation can be found here [1] 

[1] - https://central.ballerina.io/ballerinax/java.jms/latest
