### ISSUE TITLE
Can't use GraphiQL when SSL is enabled with a configurable variable for port

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-library#6459]
**Description:**
$title.

**Steps to reproduce:**

1. when I give the configurable variable directly and pass the `secureScoket` argument directly, I get a compile-time error.

```ballerina
configurable int port = 9000;

listener graphql:Listener ln = new (port,
        secureSocket = {
            key: {
                certFile: "../resources/certs/public.crt",
                keyFile: "../resources/certs/private.key"
            }
        });
```

```
ERROR [service.bal:(41:9,46:10)] http:Listener and graphql:ListenerConfiguration are mutually exclusive
```

2. when I use an http:Listener to avoid this, GraphiQL doesn't work (errors like `NetworkError when attempting to fetch resource.`, `Failed to fetch`)

```ballerina
listener graphql:Listener ln = new (check new http:Listener(port, 
        httpVersion = http:HTTP_1_1,
        secureSocket = {
            key: {
                certFile: "../resources/certs/public.crt",
                keyFile: "../resources/certs/private.key"
            }
        }));
```

Note:
1. works when using a Ballerina GraphQL client (e.g., tests work)
2. the log that is printed for GraphiQL is wrong - http instead of https - `GraphiQL client ready at http://localhost:9000/graphiql`

**Affected Versions:**
2201.9.0-rc2

**Comment by ThisaruGuruge** [comment]
This seems like an issue when validating the port in the compiler plugin. It checks whether the first argument is a numeric literal. If that's not the case, the compiler plugin throws an error assuming it is an HTTP listener. But in this case, the port is passed as a variable. 

We need to update this check to correctly validate the first argument.
