### ISSUE TITLE
Passthrough service hangs under high load

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-library#6474]
**Description:**
$Subject under load test.

Strand dump - https://gist.github.com/xlight05/af107fdd097dd6825fbe6bd6e13efa1e

Simpler sample - 

```bal
import ballerina/http;
import ballerina/log;
type Location record {|
    string name;
    string id;
    string address;
|};

type Locations record {|
    *http:Links;
    Location[] locations;
|};

final http:Client snowpeakEP = check new("http://localhost:9090");

service /passthrough on new http:Listener(9091) {
    resource function get .() returns Locations|http:InternalServerError|error {
        log:printInfo("Request received at passthrough service");
        Locations locations = check snowpeakEP->get("/snowpeak/locations");
        return locations;
    }
}

```
**Steps to reproduce:**
1. Checkout to HTTP branch with latest u9 changes
2. build a pack using ./gradlew clean build -x check -x test
3. open a new terminal and run the dependant service - `docker run -p 9090:9090 ktharmi176/snowpeak:latest`
4. run the snowpeak sample with the created pack `<http_path>/target/ballerina-runtime/bin/bal run`
5. execute the service once - `curl http://localhost:9091/passthrough`
6. Run a load test against the service - `wrk -t12 -c400 -d10s http://localhost:9091/passthrough`
7. once the load test is over, execute the service again -  `curl http://localhost:9091/passthrough`

Service should be hanging at this point.

**Affected Versions:**
2201.9.0-20240418-164300-a37919c4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
> This is wrong. We cannot block the strand thread using countdown latch or any other concurrency mechanism. We need to use markasync and future.complete methods to block the strand without blocking underlying thread.
> 
> Refer [1] for more info.
> 
> [1] https://github.com/ballerina-platform/ballerina-lang/tree/master/bvm/ballerina-runtime#calling-a-ballerina-object-method

Ack

> The logic used [here](https://github.com/ballerina-platform/module-ballerina-http/blob/8e3226c5f8cc9cb0a5e2cb043ccc140644b5e7ec/native/src/main/java/io/ballerina/stdlib/http/api/nativeimpl/ExternResponseProcessor.java#L519) which uses countdown latch can be replaced with markasync and Ballerina future. The post processing logics can be moved to the notifySuccess() method of the callback.

Ack. Since we have found a workaround in this PR: https://github.com/ballerina-platform/module-ballerina-http/pull/1954, we will use this approach for the moment

**Comment by TharmiganK** [comment]
Closing this issue since the original implementation is not valid according to the Ballerina runtime implementation
