### ISSUE TITLE
Disabled the testJwtBearerGrantType1 test as it is failing due to a certificate expiration issue

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-library#6480]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MohamedSabthar** [comment]
The test case is failing due to the certificate used in the container has expired. Hence removing the bug label. And closing the issue. Refer issue: https://github.com/ballerina-platform/ballerina-library/issues/6968 for more info
