### ISSUE TITLE
Have ballerina doc comments for public functions generated in edi `codegen` and `libgen` commands

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-library#6610]
**Description:**
$ subject

**Describe your problem(s)**
We can add doc comments to the public functions generated automatically with the edi tool.

<img width="780" alt="image" src="https://github.com/ballerina-platform/ballerina-library/assets/29953428/4b0c607e-d5d6-4f68-905f-7d3e29e476e5">

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by RDPerera** [comment]
Fixed with EDI Tools 2.0.1 release.
