### ISSUE TITLE
GRPC caller is not isolated and hence unable to make concurrent connections

### ISSUE THREAD

**Issue by ThaminduDilshan** [ballerina-platform/ballerina-library#6656]
**Description:**

I have created a grpc bi-directional client-server communication using the following proto file.
```
syntax = "proto3";

import "google/protobuf/struct.proto";

service RemoteUserStore {
    rpc communicate (stream RemoteMessage) returns (stream RemoteMessage);
}

message RemoteMessage {
    string id = 1;
    string operationType = 2;
    string organization = 3;
    google.protobuf.Struct data = 4;
}
```

The generated grpc caller (i.e. `RemoteUserStoreRemoteMessageCaller`) is not initialized as an isolated method and hence unable to make the communication method isolated to invoke concurrent requests.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dilanSachi** [comment]
This has to be fixed in both runtime and also also the protoc-tool as well

**Comment by dilanSachi** [comment]
Closing since completed
