### ISSUE TITLE
SCIM API Docs returns 500

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-library#6681]
**Description:**
$subject https://central.ballerina.io/ballerinax/scim/0.1.0

The API Docs are not loading for SCIM due to an unnecessary header in the Module.md. This was fixed via https://github.com/ballerina-platform/module-ballerinax-scim/pull/14. 

We should be able fix this by doing another release.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
@sm1990 We've released a new version to central with the aforementioned fix, and with that the API docs seem to be rendered correctly https://central.ballerina.io/ballerinax/scim/0.1.1

**Comment by NipunaRanasinghe** [comment]
Closing the issue as per https://github.com/ballerina-platform/ballerina-library/issues/6681#issuecomment-2309872262
