### ISSUE TITLE
Broken link in googleapis.cloudfilestore

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-library#6684]
**Description:**
$subject
https://central.ballerina.io/compute/docs/networks-and-firewalls#networks returns 404

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
@sm1990 Hi,

I checked both Module.md and Package.md of googleapis.cloudfilestore  and I cannot find this link.
<img width="1665" alt="Screenshot 2024-09-05 at 15 16 42" src="https://github.com/user-attachments/assets/ce49ebe8-c404-4b1b-8578-3948c6180669">
<img width="1499" alt="Screenshot 2024-09-05 at 15 16 16" src="https://github.com/user-attachments/assets/774fb07f-6dd3-498c-8b01-0931f3ca745f">
