### ISSUE TITLE
Panic occurs when generating OAuth2 token with an invalid refresh token value

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-library#6724]
**Description:**
When a `gmail:Client` is initialized with an invalid refresh token, a panic occurs instead of mapping the error value to the variable. That happens when `oauth2` module tries to generate a token using that invalid refresh token value

**Steps to reproduce:**

1. Create new Ballerina project
2. Modify the `main.bal` file as below and run the project

```ballerina
import ballerinax/googleapis.gmail;

configurable string clientId = "client-id";
configurable string clientSecret = "client-secret";
configurable string refreshToken = "refresh-token";

public function main() {
    gmail:Client|error gmail = new ({
        auth: {
            clientId,
            clientSecret,
            refreshToken
        }
    });
}
```

**Comment by MohamedSabthar** [comment]
Hi @Nuvindu, This is not a bug but a design choice. We already have an issue for this: https://github.com/ballerina-platform/ballerina-library/issues/3494
