### ISSUE TITLE
Update BBE for HTTP AccessLog

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-library#6726]
**Description:**
$title. with the changes made to HTTP AccessLog, update the [existing BBE for HTTP AccessLog](https://ballerina.io/learn/by-example/http-access-logs/) with the new changes.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayeshLK** [comment]
Closing the issue as this is already done.
- https://github.com/ballerina-platform/ballerina-distribution/pull/5582
- https://github.com/ballerina-platform/ballerina-distribution/pull/5504
