### ISSUE TITLE
Write load-tests for Http AccessLog Implementation

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-library#6738]
**Description:**
This task it to write a load test for HTTP AccessLog implementation specified in https://github.com/ballerina-platform/ballerina-library/issues/6111

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/module-ballerina-http/pull/2069
