### ISSUE TITLE
Introduce Ballerina connector templates

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-library#6745]
**Description:**

This proposal aims to introduce a new set of Ballerina connector templates to simplify and streamline the initialization process for new Ballerina connector library modules.

The primary focus of this effort is to create templates for the generated Ballerina connectors. However, the same approach can be extended to include templates for other library module types (e.g., handwritten connectors, stdlibs) in the future.

Each template will consist of workflow files, Gradle scripts, and documentation templates.

**Objectives**:
- Simplify the creation process for new connectors.
- Reduce development time by providing predefined templates.
- Ensure connectors are easy to maintain and update by adhering to a common structure.

**Action Items**:
- [ ] Create a repository to house connector templates (and also any other library templates, if needed).
- [ ] Implement a GitHub workflow to apply a selected template to a new connector repository by sending a Pull Request with the template.
- [ ] Implement additional scripts to convert the parameterized templates to connector-specific ones.

**Comment by ayeshLK** [comment]
@NipunaRanasinghe Maheshika has a template for Ballerina standard library projects (but it does not have the specific package structure and all), is it possible to improve that template into a connector/library template which package structure ?

> Create a repository to house connector templates (and also any other library templates, if needed).

For this I think we might not need a repository itself, we could add this template into the `ballerina-library` repository (inside a directory called `templates` or `library-templates`) and use that.

**Comment by ThisaruGuruge** [comment]
> @NipunaRanasinghe Maheshika has a template for Ballerina standard library projects (but it does not have the specific package structure and all), is it possible to improve that template into a connector/library template which package structure ?

I think we have considered this option and selected the other option due to some limitations in GitHub templates. GitHub templates aren't actually templates, it seems :)
 
> For this I think we might not need a repository itself, we could add this template into the `ballerina-library` repository (inside a directory called `templates` or `library-templates`) and use that.

+1

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe Maheshika has a template for Ballerina standard library projects (but it does not have the specific package structure and all), is it possible to improve that template into a connector/library template which package structure ?

As Thisaru already mentioned, we have evaluated the GitHub template repository option, but they still do not support variables (as discussed [here](https://github.com/orgs/community/discussions/5336)). This is one reason we have chosen our current approach.

Additionally, the proposed approach will be more scalable because I anticipate the number of templates to continue growing over time (For example, we will need to maintain separate templates for S4HANA-generated connectors). Therefore, having control over these templates on our side would be the better option, IMO.

> For this I think we might not need a repository itself, we could add this template into the `ballerina-library` repository (inside a directory called `templates` or `library-templates`) and use that.
yes that makes more sense. +1
