### ISSUE TITLE
Should be a way to define the authentication mechanism in SFTP client

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#6764]
**Description:**
$subject

https://github.com/ballerina-platform/module-ballerina-ftp/blob/master/native/src/main/java/io/ballerina/stdlib/ftp/transport/server/util/FileTransportUtils.java#L85

This should be configurable. The issue here is we cannot support interactive authentication in ballerina client. The users have no way to disable it in case of Kerberos authentication.

**Comment by dilanSachi** [comment]
Closing since completed
