### ISSUE TITLE
Allow customizable authentication methods in SFTP client

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-library#6768]
**Description:**

Currently, the Ballerina SFTP connector supports several authentication methods such as `gssapi-with-mic`, `publickey`, `keyboard-interactive`, and `password`. However, user can't specify only the auth methods they require at the moment,
which may lead to some usability issues such as getting unnecessary Kerberos auth requirements each time a SFTP client is initialized (This can be fixed by only using `publickey` instead of having `keyboard-interactive`)

**Comment by dilanSachi** [comment]
Related - https://github.com/ballerina-platform/ballerina-library/issues/6764
