### ISSUE TITLE
[Proposal] Enhanced Usability for SAP JCo Function Execution in Ballerina with Multiple Parameters

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-library#6783]
This proposal outlines the mapping of JCo data types to Ballerina data types for the SAP JCo Connector. The objective is to ensure accurate and efficient data exchange between SAP systems and Ballerina applications by providing clear and consistent mappings for both import (setters) and export (getters) parameter types.

### JCo to Ballerina Data Type Mapping

| ABAP Type  | Description                           | Ballerina Type         |
|------------|---------------------------------------|------------------------|
| CHAR       | Fixed-length character string         | `string`               |
| CHAR       | Single character                      | `string`               |
| NUMC       | Numeric text                          | `string`               |
| INT1       | 1-byte integer                        | `int`                  |
| INT2       | 2-byte integer                        | `int`                  |
| INT4       | 4-byte integer                        | `int`                  |
| INT8       | 8-byte integer (if supported)         | `int`                  |
| FLTP       | Floating-point number                 | `float`                |
| DEC        | Packed decimal                        | `decimal`              |
| RAW/XSTR   | Variable-length byte string           | `byte[]`               |
| CHAR/FLAG  | Character representing true/false (e.g., 'X' for true) | `boolean`              |
| DATS       | Date in the format YYYYMMDD           | `time:Date`            |
| TIMS       | Time in the format HHMMSS             | `time:TimeOfDay`            |
| DATS/TIMS  | Combination of date and time          | `time:Utc`        |
| LANG       | Language key                          | `string`               |
| CUKY       | Currency key                          | `string`               |
| QUAN       | Quantity field                        | `decimal`              |
| UNIT       | Unit of measure                       | `string`               |

| Complex ABAP Type  | Description                           | Ballerina Type         |
|------------|---------------------------------------|------------------------|
| STRUCTURE  | Group of fields                       | `record {}`            |
| TABLE      | Multi-row dataset, array of structures| `record{}[]`    |

**Comment by niveathika** [comment]
When considering the usecase for input parameters and output parameters, the RFC accepts multiple values. To improve usability we can introduce two functions,
```ballerina
public type FieldType string|int|float|decimal|boolean|byte[]|time:Date|time:TimeOfDay|time:Utc|record {|FieldType...;|}|record {|FieldType...;|}[];

isolated remote function execute(string functionName, FieldType? importParams = (), typedesc<FieldType|FieldType[]|map<FieldType>|xml|json?> exportParams = <>) returns exportParams|Error;

isolated remote function executeWithMultipleParams(string functionName, FieldType[]|map<FieldType>? importParams = (), typedesc<FieldType|FieldType[]|map<FieldType>|xml|json?> exportParams = <>) returns exportParams|Error;
```

`execute()` can be used when there is only one input paramerters and `executeWithMultipleParams` can be used for multiple values. 

For the output return, all simple types can be used to bind to specific types,
```
// Returns one string field
string _ = check jcoClient->execute("", "a");
// Returns multiple fields in order
FieldType[] _ = check jcoClient->execute("", "a");
// Returns multiple fields with param names
map<string> _ = check jcoClient->execute("", "a");

// Returns on JCOStructure
record{||} _ = check jcoClient->execute("", "a");
// Returns on JCOStructure with param names
map<record{||}> _ = check jcoClient->execute("", "a");

// Returns Table
record{||}[] _ = check jcoClient->execute("", "a");
// Return multiple tables in positional value
record{||}[][] _ = check jcoClient->execute("", "a");
```
Here only exception is to get multiple JCO structure in an array,
```ballerina
public annotation MultiStructure on type;

@MultiStructure
type MultipleValues record{||}[];

MultipleValues _ = check jcoClient->execute("", "a");
```
This exception is to solve the confusion as if the user expects one return value of table type or multiple JCO structure in an array.
