### ISSUE TITLE
Replace the Package.md and Module.md files with README.md File

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-library#6802]
**Description:**

The Ballerina Libraries should use the `README.md` file instead of `Package.md` and `Module.md` files going forward. This should be done for the packages that should be released with the Ballerina SwanLake Update 10.

Refer this issue: https://github.com/ballerina-platform/ballerina-lang/issues/42981

**Comment by ayeshLK** [comment]
As the original PR has been reverted [1] we will have to wait before working on this.

[1] - https://github.com/ballerina-platform/ballerina-lang/pull/43218

**Comment by ThisaruGuruge** [comment]
Closing the issue since this is not deferred from Update 10.
