### ISSUE TITLE
Add BINARY Clause Encoding Mechanism to Copybook 

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-library#6886]
**Description:**
>$subject

The BINARY fields use a different encoding mechanism compared to the standard fields. The following resource that explains the encoding steps.
http://www.simotime.com/databn01.htm

**Comment by MohamedSabthar** [comment]
With this support we need to add the following API in `copybook:Converter` class

```ballerina
    public enum Encoding {
        ASCII,
        EBCDIC
    }

    private isolated function toBytes(typedesc<record {}> t, string? targetRecordName = (),
        Encoding encoding = ASCII) returns byte[]|Error {
        // ...
    }

    private isolated function fromBytes(byte[] bytes, string? targetRecordName = (),
        Encoding encoding = ASCII,  typedesc<record {}> t = <>) returns t|Error {
        // ...
    }
```

based on the encoding functions mentioned here can be called internally to handle the conversion: https://github.com/ballerina-platform/ballerina-library/issues/6892
