### ISSUE TITLE
Add Support for Retrieving Messages from IBM MQ by Matching Correlation ID and Message ID

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-library#6918]
**Description:**
There is a requirement to obtain the message from the IBM-MQ using Correlation ID and/or Message ID. 
For more information about obtaining message using matching Ids refer:  https://www.ibm.com/docs/en/ibm-mq/9.4?topic=descriptor-msgid-mqbyte24-mqmd

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayeshLK** [comment]
To support the above change we need to do following API changes.

#### Introduce `ibmmq:MatchOptions` record type

```ballerina
# Represents the selection criteria that determine which message is retrieved.
#
# + messageId - The message identifier of the message which needs to be retrieved
# + correlationId - The Correlation identifier of the message which needs to be retrieved
public type MatchOptions record {|
    byte[] messageId?;
    byte[] correlationId?;
|};
```

#### Include `ibmmq:MatchOptions` as an optional parameter to `ibmmq:GetMessageOptions` record type

```ballerina
# IBM MQ get message options.
#
# + matchOptions - Message selection criteria
public type GetMessageOptions record {|
    // other fields
    MatchOptions matchOptions?;
|};
```

@NipunaRanasinghe please review.

**Comment by ayeshLK** [comment]
According to the IBM MQ documentation [1][2], when retrieving messages from a queue or a topic, multiple identifiers such as `messageId` and `correlationId` can be used together for message selection. Therefore, during implementation, specifying both `messageId` and `correlationId` means that only messages that match both of these identifiers will be selected.

[1] - [IBM MQ - MQGMO Options](https://www.ibm.com/docs/en/ibm-mq/9.4?topic=options-matchoptions-mqlong-mqgmo)
[2] - [IBM MQ - Getting a Particular Message from a Queue](https://www.ibm.com/docs/en/ibm-mq/9.4?topic=queue-getting-particular-message)

**Comment by ayeshLK** [comment]
> ```ballerina
> MQMI_NONE
> ```

As per the documentation [1];

> The message identifier MQMI_NONE is a special value that matches any message identifier in the MQMD for the message. Therefore, specifying MQMO_MATCH_MSG_ID with MQMI_NONE is the same as not specifying MQMO_MATCH_MSG_ID. 

Same applies to the `correlationId` field as well. Hence marking the `messageId` and `correlationId` as optional would suffice IMO.

[1] - https://www.ibm.com/docs/en/ibm-mq/9.4?topic=options-matchoptions-mqlong-mqgmo

**Comment by ayeshLK** [comment]
> @ayeshLK Ack. As per the offline discussion we had, then its okay to proceed with the existing design.
> 
> One minor improvement we can do is to use `MQMI_NONE` and `MQCI_NONE` as the default values for the messageId and correlationId, respectively.
> 
> ```ballerina
> public type MatchOptions record {|
>     byte[] messageId = MQMI_NONE;
>     byte[] correlationId = MQCI_NONE;
> |};
> ```
> 
> wdyt?


As per the documentation [1];

> The message identifier MQMI_NONE is a special value that matches any message identifier in the MQMD for the message. Therefore, specifying MQMO_MATCH_MSG_ID with MQMI_NONE is the same as not specifying MQMO_MATCH_MSG_ID. 

Same applies to the `correlationId` field as well. Hence marking the `messageId` and `correlationId` as optional would suffice IMO.

[1] - https://www.ibm.com/docs/en/ibm-mq/9.4?topic=options-matchoptions-mqlong-mqgmo
