### ISSUE TITLE
Receive invalid type casting issue while using data.json data module with test

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#7024]
**Description:**

This error[1] occurs when we are using data.jsondata for adding test in http module 
```
error: compilation failed: The compiler extension in package 'ballerina:data.jsondata:0.3.0' failed to complete. class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BAnnotationSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BAnnotationSymbol are in unnamed module of loader 'app')
```
**Steps to reproduce:**
Please use the package HTTP-client-test to reproduce this issue : https://github.com/ballerina-platform/module-ballerina-http/pull/2151

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
@SasinduDilshara Please update once this issue is fixed since this is a major blocker to the PR which we migrated lang util into data.jsondata utils to within the HTTP module https://github.com/ballerina-platform/module-ballerina-http/pull/2151

**Comment by SasinduDilshara** [comment]
This is the simplest case for this issue.

```
import ballerina/data.jsondata;

public type TPerson record {
    @jsondata:Name {
        value: "name"
    }
    string firstName;
    @jsondata:Name {
        value: "age"
    }
    string personAge;
};

public type MetaInfo record {|
    string name;
|};

public const annotation MetaInfo Meta on record field;
public type QueryWithDifferentAnnotation record {|
    // @http:Query {name: "first-name"}
    @Meta {
        name: "Potter"
    }
    string firstName;
    int age;
|};
```

**Comment by SasinduDilshara** [comment]
When the above definitions are defined inside the `tests` module, it will gives the `class cast exception` error.
but if it inside a non-test module, it will work fine

As a workaround you have to move the type definitions with annotations into the relevent non-test module.

**Comment by SasinduDilshara** [comment]
Create a new issue to track the main issue inside here

https://github.com/ballerina-platform/ballerina-lang/issues/43423

**Comment by lnash94** [comment]
@SasinduDilshara Since this is a temporary workaround, we are unable to merge the PRs. Therefore may we know the ETA for this fix?

**Comment by SasinduDilshara** [comment]
> @SasinduDilshara Since this is a temporary workaround, we are unable to merge the PRs. Therefore may we know the ETA for this fix?

This will be fix with U11.

Will make this as a High priority issue

**Comment by SasinduDilshara** [comment]
> Create a new issue to track the main issue inside here
> 
> [ballerina-platform/ballerina-lang#43423](https://github.com/ballerina-platform/ballerina-lang/issues/43423)

Closed since, https://github.com/ballerina-platform/ballerina-lang/issues/43423 got fixed now
