### ISSUE TITLE
Invalid error for readonly record field in `data.jsondata` module in `parseAsType` API

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-library#7259]
```
import ballerina/io;
import ballerina/data.jsondata;

type DDPerson record {|
    readonly int id;
|};

public function main() returns error? {
    json user2 =  {"id": 4012};
    DDPerson r2 = check jsondata:parseAsType(user2);
    io:println(r2.id);
}
```

The above code give following error

```
error: {ballerina}TypeCastError {"message":"incompatible types: 'error' cannot be cast to '(anydata|data.jsondata:Error)'"}
        at ballerina.data.jsondata.0:parseString(json_api.bal:33)
           wso2.jsontest.0:main(main.bal:10)
```

**Comment by lnash94** [comment]
This issue is a blocker for the module http , jsondata APIs migration in u11. https://github.com/ballerina-platform/module-ballerina-http/pull/2168
And provide this support : https://github.com/ballerina-platform/ballerina-library/issues/4870#issuecomment-2262151011

**Comment by SasinduDilshara** [comment]
https://github.com/ballerina-platform/module-ballerina-data.jsondata/pull/46 Will fix this issue for the `parseAstype` API which is the blocker for the module http.

The same issue occurs for the `parseString` API (Currently not a blocker) is track by https://github.com/ballerina-platform/ballerina-library/issues/7302
