### ISSUE TITLE
Jsondata moduel `toJson` is hanging with the `CyclicValueReferenceError` error

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#7326]
### Description

with the 0.2.0 jasondata version we recieved the expected error [1] from the jsondata for the following sample[2], when doing `bal run`
[1] Expected error
```
error: {ballerina/lang.value}CyclicValueReferenceError {"message":"'json[]' value has cyclic reference"}
        at ballerina.data.jsondata.0:toJson(json_api.bal:58)
           hansaninissanka.jsondata.0:main(main.bal:10)
```
[2]Ballerina sample
```ballerina
import ballerina/io;
import ballerina/data.jsondata;

public function main() returns error? {
    io:println("Hello, World!");

    json[] x = [];
    x.push(x);
    json _  = check jsondata:toJson(x);
}
```
but with  the timestamp `0.3.0-20241028-143400-903c253`  of jsondata module , this particular example getting hang in `bal run` command 

### Steps to Reproduce

`bal run` the above [2] ballerina sample with the jsondata.module version `0.3.0-20241028-143400-903c253`

### Version

0.3.0-20241028-143400-903c253

**Comment by lnash94** [comment]
We disable this negative tests in http module https://github.com/ballerina-platform/ballerina-library/issues/7021#:~:text=Enable%20this%20negative%20test , let us know once this is enable

**Comment by TharmiganK** [comment]
Please note that this is a regression issue, the same code is working as expected in the `0.2.0` version, but with the recent timestamp it is hanging.

**Comment by MaryamZi** [comment]
Introduced by https://github.com/ballerina-platform/module-ballerina-data.jsondata/pull/35, since cyclic values are not handled with mappings and lists.
