### ISSUE TITLE
Missing namespace information in generated XML for records with type inclusion

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-library#7403]
### Description

When converting a record type annotated with `@xmldata:Namespace` to XML using the `xmldata:toXml()` function, the generated XML does not include the namespace information specified in the annotations.

### Steps to Reproduce

1. Run the following sample code

```ballerina
import ballerina/data.xmldata;
import ballerina/io;

@xmldata:Namespace {prefix: "soap", uri: "http://www.w3.org/2003/05/soap-envelope"}
public type Envelope record {
    *Body;
};

@xmldata:Namespace {prefix: "xs2", uri: "http://www.w3.org/2001/XMLSchema2"}
public type Body record {
    @xmldata:Namespace {prefix: "xs1", uri: "http://www.w3.org/2001/XMLSchema1"}
    string value;
};

public function main() returns error? {
    Envelope document = {
        value: "this is a string"
    };
    xml xmlDocument = check xmldata:toXml(document);
    io:println(xmlDocument);
}
```
Result:
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><value>this is a string</value></soap:Envelope>`

Expected Result:
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><value xmlns:xs1="http://www.w3.org/2001/XMLSchema1">this is a string</value></soap:Envelope>`

### Version

2201.10.2

**Comment by SasinduDilshara** [comment]
This happen because, the included records does not inherit its metadata informations.
Related spec issue - https://github.com/ballerina-platform/ballerina-spec/issues/1311

So this issue should be fixed from the language repository.

**Comment by SasinduDilshara** [comment]
Closed due to https://github.com/ballerina-platform/ballerina-library/issues/7403#issuecomment-2497216696
