### ISSUE TITLE
Generated OAS spec need to have require fields for record which has default value in different package

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#7415]
### Description

Follow the below example :

### Steps to Reproduce

This `RollingWindow` record belongs to a different package  `packageA`
```ballerina
public type RollingWindow record {|
    decimal timeWindow = 60;
    decimal bucketSize = 10;
|};
```
if we are using it in the service from another package
```ballerina
...
service / on new http:Listener(7080) {
    resource function get Services() returns packageA:RollingWindow[] {
        return [];
    }
}
```
The generated OAS includes `RollingWindow` fields as optional fields, but it should be marked as required since we currently cannot map a default value from a different package.

### Version

2201.10.0

**Comment by TharmiganK** [comment]
This is invalid. This is specific to ballerina to spec generation limitations. Even though we don't map the default value, ballerina program will anyway consider this as an optional filed. In that case, it is not correct to consider it as required. Ultimately, when we fix this default value limitation, it should remain as optional field. Hence closing this issue
