### ISSUE TITLE
Checking openapi hanging issue 

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#7444]
### Description

$Subject
with lang time stamp: 2201.11.0-20241204-163800-0d1e4836

**Comment by TharmiganK** [comment]
This is due to this lang issue: https://github.com/ballerina-platform/ballerina-lang/issues/43688

**Comment by lnash94** [comment]
We have tests failure with i openapi tool with this fix https://github.com/ballerina-platform/ballerina-lang/pull/43689

**Comment by lnash94** [comment]
PR for disable the tests: https://github.com/ballerina-platform/openapi-tools/pull/1801
